// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class EximbayV2Surcharge {
  /// **항목명**
  final String name;

  /// **수량**
  final String quantity;

  /// **단가 (음수 가능)**
  final String unitPrice;

  EximbayV2Surcharge({
    required this.name,
    required this.quantity,
    required this.unitPrice,
  });

  Map<String, dynamic> toJson() => {
    'name': name,
    'quantity': quantity,
    'unit_price': unitPrice,
  };
}
