// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 결제 정보
class EximbayV2Payment {
  /// 결제수단 단독 노출
  final String? paymentMethod;

  /// 결제수단 노출 목록
  final List<String>? multiPaymentMethod;

  EximbayV2Payment({this.paymentMethod, this.multiPaymentMethod});

  Map<String, dynamic> toJson() => {
    if (paymentMethod != null) 'payment_method': paymentMethod!,
    if (multiPaymentMethod != null) 'multi_payment_method': multiPaymentMethod!,
  };

  static EximbayV2Payment fromJson(Map<String, dynamic> json) =>
      EximbayV2Payment(
        paymentMethod: json['payment_method'] as String?,
        multiPaymentMethod:
            (json['multi_payment_method'] as List?)?.cast<String>(),
      );
}
