// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class EximbayV2Merchant {
  /// **상점명**
  final String shop;

  EximbayV2Merchant({required this.shop});

  Map<String, dynamic> toJson() => {'shop': shop};
}
