// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key_and_pay/eximbay_v_2_payment.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_bill_to.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_merchant.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_ship_to.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_surcharge.dart';

/// **엑심베이 bypass 파라미터**
class EximbayV2IssueBillingKeyAndPayBypass {
  /// 결제 정보
  final EximbayV2Payment? payment;

  /// 상점 정보
  final EximbayV2Merchant? merchant;

  /// **최대 3개의 추가 비용 목록**
  final List<EximbayV2Surcharge>? surcharge;

  /// 배송지 정보
  final EximbayV2ShipTo? shipTo;

  /// 청구지 정보
  final EximbayV2BillTo? billTo;

  EximbayV2IssueBillingKeyAndPayBypass({
    this.payment,
    this.merchant,
    this.surcharge,
    this.shipTo,
    this.billTo,
  });

  Map<String, dynamic> toJson() => {
    if (payment != null) 'payment': payment!.toJson(),
    if (merchant != null) 'merchant': merchant!.toJson(),
    if (surcharge != null)
      'surcharge': surcharge!.map((e) => e.toJson()).toList(),
    if (shipTo != null) 'shipTo': shipTo!.toJson(),
    if (billTo != null) 'billTo': billTo!.toJson(),
  };

  static EximbayV2IssueBillingKeyAndPayBypass fromJson(
    Map<String, dynamic> json,
  ) => EximbayV2IssueBillingKeyAndPayBypass(
    payment:
        json['payment'] != null
            ? EximbayV2Payment.fromJson(json['payment'])
            : null,
    merchant:
        json['merchant'] != null
            ? EximbayV2Merchant.fromJson(json['merchant'])
            : null,
    surcharge:
        (json['surcharge'] as List?)
            ?.map((e) => EximbayV2Surcharge.fromJson(e))
            .toList(),
    shipTo:
        json['shipTo'] != null
            ? EximbayV2ShipTo.fromJson(json['shipTo'])
            : null,
    billTo:
        json['billTo'] != null
            ? EximbayV2BillTo.fromJson(json['billTo'])
            : null,
  );
}
