// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **청구지 정보**
class EximbayV2BillTo {
  /// **청구지 도시**
  final String city;

  /// **청구지 국가 (ISO 3166 두 자리 국가 코드)**
  final String country;

  /// **청구 카드 명의자의 성을 제외한 이름**
  final String firstName;

  /// **청구 카드 명의자의 성**
  final String lastName;

  /// **청구 카드 명의자의 전화번호**
  final String phoneNumber;

  /// **청구지 우편번호**
  final String postalCode;

  /// **청구지가 미국 혹은 캐나다인 경우, 청구지 주 정보**
  final String state;

  /// **청구지 상세 주소**
  final String street1;

  EximbayV2BillTo({
    required this.city,
    required this.country,
    required this.firstName,
    required this.lastName,
    required this.phoneNumber,
    required this.postalCode,
    required this.state,
    required this.street1,
  });

  Map<String, dynamic> toJson() => {
    'city': city,
    'country': country,
    'first_name': firstName,
    'last_name': lastName,
    'phone_number': phoneNumber,
    'postal_code': postalCode,
    'state': state,
    'street1': street1,
  };
}
