// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **갤럭시아 bypass 파라미터**
class GalaxiaIssueBillingKeyAndPayBypass {
  /// 구매 상품 코드
  final String? itemCode;

  GalaxiaIssueBillingKeyAndPayBypass({this.itemCode});

  Map<String, dynamic> toJson() => {
    if (itemCode != null) 'ITEM_CODE': itemCode!,
  };

  static GalaxiaIssueBillingKeyAndPayBypass fromJson(
    Map<String, dynamic> json,
  ) => GalaxiaIssueBillingKeyAndPayBypass(
    itemCode: json['ITEM_CODE'] as String?,
  );
}
