// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **페이레터 해외결제 bypass 파라미터**
class PayletterGlobalIssueBillingKeyAndPayBypass {
  /// **결제수단 지정용 파라미터**
  ///
  /// - 해외카드 비인증 : `PLCreditCard`
  /// - 해외카드 인증(3DS) : `PLCreditCardMpi`
  /// - 유니온페이 : `PLUnionPay_HC`
  /// - 위챗페이 PC결제: `WeChatPayQRCodePayment`
  /// - 위챗페이 모바일결제 : `WeChatPayH5Payment`
  /// - 알리페이 : `ICBAlipay`
  final String? pginfo;

  /// 고객사 서비스명, WeChatPay, Alipay 이용 시 필수 입력
  final String? servicename;

  PayletterGlobalIssueBillingKeyAndPayBypass({this.pginfo, this.servicename});

  Map<String, dynamic> toJson() => {
    if (pginfo != null) 'pginfo': pginfo!,
    if (servicename != null) 'servicename': servicename!,
  };

  static PayletterGlobalIssueBillingKeyAndPayBypass fromJson(
    Map<String, dynamic> json,
  ) => PayletterGlobalIssueBillingKeyAndPayBypass(
    pginfo: json['pginfo'] as String?,
    servicename: json['servicename'] as String?,
  );
}
