// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **웰컴페이먼츠 bypass 파라미터**
class WelcomeIssueBillingKeyAndPayBypass {
  /// `acceptmethod` 파라미터는 휴대폰 소액결제 시 기본 선택할 통신사를 설정하며, 추가로 `buyer_tel` 값의 수정 가능 여부를 지정할 수 있습니다.
  ///
  /// **통신사 기본 선택 설정:**
  ///
  /// - 특정 통신사를 기본 선택하려면 `hppdefaultcorp(통신사코드)` 형식으로 전달합니다.
  /// - 예시: KT를 기본 선택 → `hppdefaultcorp(KTF)`
  ///
  /// **가능한 통신사 코드:**
  ///
  /// - `SKT`: SK 텔레콤
  /// - `KTF`: KT
  /// - `LGT`: LG 유플러스
  /// - `MVNO`: 알뜰폰 전체
  /// - `CJH`: 알뜰폰 CJ 헬로 모바일
  /// - `KCT`: 알뜰폰 티플러스
  /// - `SKL`: 알뜰폰 SK 세븐 모바일
  ///
  /// **휴대폰 소액결제창에 자동 입력되는 `buyer_tel` 수정 가능 여부 설정:**
  ///
  /// - 수정 불가능으로 설정하려면 `hppnofix(Y)`를 전달합니다.
  /// - 수정 가능으로 설정하려면 `hppnofix(N)`를 전달합니다. (기본값)
  final List<String>? acceptmethod;

  /// `P_RESERVED` 파라미터는 휴대폰 소액결제 시 기본 선택할 통신사를 설정하며, 추가로 `buyer_tel` 값의 수정 가능 여부를 지정할 수 있습니다.
  ///
  /// **통신사 기본 선택 설정:**
  ///
  /// - 특정 통신사를 기본 선택하려면 `hpp_default_corp=통신사코드` 형식으로 전달합니다.
  /// - 예시: KT를 기본 선택 → `hpp_default_corp=KTF`
  ///
  /// **가능한 통신사 코드:**
  ///
  /// - `SKT`: SK 텔레콤
  /// - `KTF`: KT
  /// - `LGT`: LG 유플러스
  /// - `MVNO`: 알뜰폰 전체
  /// - `CJH`: 알뜰폰 CJ 헬로 모바일
  /// - `KCT`: 알뜰폰 티플러스
  /// - `SKL`: 알뜰폰 SK 세븐 모바일
  ///
  /// **휴대폰 소액결제창에 자동 입력되는 `buyer_tel` 수정 가능 여부 설정:**
  ///
  /// - 수정 불가능으로 설정하려면 `hpp_nofix=Y`를 전달합니다.
  /// - 수정 가능으로 설정하려면 `hpp_nofix=N`를 전달합니다. (기본값)
  final List<String>? pReserved;

  WelcomeIssueBillingKeyAndPayBypass({this.acceptmethod, this.pReserved});

  Map<String, dynamic> toJson() => {
    if (acceptmethod != null) 'acceptmethod': acceptmethod!,
    if (pReserved != null) 'P_RESERVED': pReserved!,
  };

  static WelcomeIssueBillingKeyAndPayBypass fromJson(
    Map<String, dynamic> json,
  ) => WelcomeIssueBillingKeyAndPayBypass(
    acceptmethod: (json['acceptmethod'] as List?)?.cast<String>(),
    pReserved: (json['P_RESERVED'] as List?)?.cast<String>(),
  );
}
