// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/country.dart';

/// **주소 정보**
class Address {
  /// **국가**
  ///
  /// [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
  final Country? country;

  /// **주소 첫째 줄**
  final String addressLine1;

  /// **주소 둘째 줄**
  final String addressLine2;

  /// **도시**
  final String? city;

  /// **주, 도, 시**
  final String? province;

  Address({
    this.country,
    required this.addressLine1,
    required this.addressLine2,
    this.city,
    this.province,
  });

  Map<String, dynamic> toJson() => {
    if (country != null) 'country': country!.toJson(),
    'addressLine1': addressLine1,
    'addressLine2': addressLine2,
    if (city != null) 'city': city!,
    if (province != null) 'province': province!,
  };

  static Address fromJson(Map<String, dynamic> json) => Address(
    country: json['country'] != null ? Country.fromJson(json['country']) : null,
    addressLine1: json['addressLine1'] as String,
    addressLine2: json['addressLine2'] as String,
    city: json['city'] as String?,
    province: json['province'] as String?,
  );
}
