// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 빌링키 발급 및 초회결제 수단
enum BillingKeyAndPayMethod {
  /// 휴대전화
  MOBILE('MOBILE');

  final String _value;
  const BillingKeyAndPayMethod(String value) : _value = value;
  String toJson() => _value;
}
