// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 빌링키 발급 수단
enum BillingKeyMethod {
  /// 카드
  CARD('CARD'),

  /// 휴대전화
  MOBILE('MOBILE'),

  /// 간편결제
  EASY_PAY('EASY_PAY'),

  /// 페이팔(RT)
  PAYPAL('PAYPAL');

  final String _value;
  const BillingKeyMethod(String value) : _value = value;
  String toJson() => _value;
  static BillingKeyMethod fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
