// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **카드 프로모션 정보**
///
/// 카드사 다이렉트 호출 시 적용할 카드사 할인 쿠폰 정보입니다.
///
/// 현재 KCP\_V2 채널에서만 사용 가능합니다.
class CardPromotion {
  /// **프로모션 ID**
  ///
  /// 카드사에서 제공하는 프로모션 식별자입니다.
  final String promotionId;

  /// **할인 금액**
  ///
  /// 프로모션으로 할인받을 금액입니다.
  final int discountAmount;

  CardPromotion({required this.promotionId, required this.discountAmount});

  Map<String, dynamic> toJson() => {
    'promotionId': promotionId,
    'discountAmount': discountAmount,
  };
}
