// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 카드 결제시 사용되는 카드사 코드
enum CardCompany {
  /// KDB산업은행 카드
  KOREA_DEVELOPMENT_BANK('KOREA_DEVELOPMENT_BANK'),

  /// 새마을금고 카드
  KFCC('KFCC'),

  /// 신협 카드
  SHINHYUP('SHINHYUP'),

  /// 우체국 카드
  EPOST('EPOST'),

  /// 저축은행 카드
  SAVINGS_BANK_KOREA('SAVINGS_BANK_KOREA'),

  /// 카카오뱅크 카드
  KAKAO_BANK('KAKAO_BANK'),

  /// 우리카드
  WOORI_CARD('WOORI_CARD'),

  /// BC카드
  BC_CARD('BC_CARD'),

  /// 광주카드
  GWANGJU_CARD('GWANGJU_CARD'),

  /// 삼성카드
  SAMSUNG_CARD('SAMSUNG_CARD'),

  /// 신한카드
  SHINHAN_CARD('SHINHAN_CARD'),

  /// 현대카드
  HYUNDAI_CARD('HYUNDAI_CARD'),

  /// 롯데카드
  LOTTE_CARD('LOTTE_CARD'),

  /// 수협카드
  SUHYUP_CARD('SUHYUP_CARD'),

  /// 씨티카드
  CITI_CARD('CITI_CARD'),

  /// NH 농협카드
  NH_CARD('NH_CARD'),

  /// 전북카드
  JEONBUK_CARD('JEONBUK_CARD'),

  /// 제주카드
  JEJU_CARD('JEJU_CARD'),

  /// 하나카드
  HANA_CARD('HANA_CARD'),

  /// 국민카드
  KOOKMIN_CARD('KOOKMIN_CARD'),

  /// K뱅크 카드
  K_BANK('K_BANK'),

  /// 토스뱅크 카드
  TOSS_BANK('TOSS_BANK'),

  /// 미래에셋증권 카드
  MIRAE_ASSET_SECURITIES('MIRAE_ASSET_SECURITIES');

  final String _value;
  const CardCompany(String value) : _value = value;
  String toJson() => _value;
  static CardCompany fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
