// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 통신사 코드
enum Carrier {
  /// SK텔레콤
  SKT('SKT'),

  /// KT
  KT('KT'),

  /// LG U+
  LGU('LGU'),

  /// 헬로모바일
  HELLO('HELLO'),

  /// 티플러스
  KCT('KCT'),

  /// SK 7mobile
  SK7('SK7');

  final String _value;
  const Carrier(String value) : _value = value;
  String toJson() => _value;
  static Carrier fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
