// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **현금영수증 발급 유형**
enum CashReceiptType {
  /// 소득공제(개인)
  PERSONAL('PERSONAL'),

  /// 지출증빙(사업자)
  CORPORATE('CORPORATE'),

  /// 미발행(PG 설정에 따라 무기명으로 자진 발급될 수 있음)
  ANONYMOUS('ANONYMOUS');

  final String _value;
  const CashReceiptType(String value) : _value = value;
  String toJson() => _value;
}
