// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **국가**
///
/// [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
enum Country {
  /// Afghanistan
  AF('AF'),

  /// Åland Islands
  AX('AX'),

  /// Albania
  AL('AL'),

  /// Algeria
  DZ('DZ'),

  /// American Samoa
  AS('AS'),

  /// Andorra
  AD('AD'),

  /// Angola
  AO('AO'),

  /// Anguilla
  AI('AI'),

  /// Antarctica
  AQ('AQ'),

  /// Antigua and Barbuda
  AG('AG'),

  /// Argentina
  AR('AR'),

  /// Armenia
  AM('AM'),

  /// Aruba
  AW('AW'),

  /// Australia
  AU('AU'),

  /// Austria
  AT('AT'),

  /// Azerbaijan
  AZ('AZ'),

  /// Bahrain
  BH('BH'),

  /// Bahamas
  BS('BS'),

  /// Bangladesh
  BD('BD'),

  /// Barbados
  BB('BB'),

  /// Belarus
  BY('BY'),

  /// Belgium
  BE('BE'),

  /// Belize
  BZ('BZ'),

  /// Benin
  BJ('BJ'),

  /// Bermuda
  BM('BM'),

  /// Bhutan
  BT('BT'),

  /// Bolivia, Plurinational State of
  BO('BO'),

  /// Bonaire, Sint Eustatius and Saba
  BQ('BQ'),

  /// Bosnia and Herzegovina
  BA('BA'),

  /// Botswana
  BW('BW'),

  /// Bouvet Island
  BV('BV'),

  /// Brazil
  BR('BR'),

  /// British Indian Ocean Territory
  IO('IO'),

  /// Brunei Darussalam
  BN('BN'),

  /// Bulgaria
  BG('BG'),

  /// Burkina Faso
  BF('BF'),

  /// Burundi
  BI('BI'),

  /// Cambodia
  KH('KH'),

  /// Cameroon
  CM('CM'),

  /// Canada
  CA('CA'),

  /// Cape Verde
  CV('CV'),

  /// Cayman Islands
  KY('KY'),

  /// Central African Republic
  CF('CF'),

  /// Chad
  TD('TD'),

  /// Chile
  CL('CL'),

  /// China
  CN('CN'),

  /// Christmas Island
  CX('CX'),

  /// Cocos (Keeling) Islands
  CC('CC'),

  /// Colombia
  CO('CO'),

  /// Comoros
  KM('KM'),

  /// Congo
  CG('CG'),

  /// Congo, the Democratic Republic of the
  CD('CD'),

  /// Cook Islands
  CK('CK'),

  /// Costa Rica
  CR('CR'),

  /// Côte d'Ivoire
  CI('CI'),

  /// Croatia
  HR('HR'),

  /// Cuba
  CU('CU'),

  /// Curaçao
  CW('CW'),

  /// Cyprus
  CY('CY'),

  /// Czech Republic
  CZ('CZ'),

  /// Denmark
  DK('DK'),

  /// Djibouti
  DJ('DJ'),

  /// Dominica
  DM('DM'),

  /// Dominican Republic
  DO('DO'),

  /// Ecuador
  EC('EC'),

  /// Egypt
  EG('EG'),

  /// El Salvador
  SV('SV'),

  /// Equatorial Guinea
  GQ('GQ'),

  /// Eritrea
  ER('ER'),

  /// Estonia
  EE('EE'),

  /// Ethiopia
  ET('ET'),

  /// Falkland Islands (Malvinas)
  FK('FK'),

  /// Faroe Islands
  FO('FO'),

  /// Fiji
  FJ('FJ'),

  /// Finland
  FI('FI'),

  /// France
  FR('FR'),

  /// French Guiana
  GF('GF'),

  /// French Polynesia
  PF('PF'),

  /// French Southern Territories
  TF('TF'),

  /// Gabon
  GA('GA'),

  /// Gambia
  GM('GM'),

  /// Georgia
  GE('GE'),

  /// Germany
  DE('DE'),

  /// Ghana
  GH('GH'),

  /// Gibraltar
  GI('GI'),

  /// Greece
  GR('GR'),

  /// Greenland
  GL('GL'),

  /// Grenada
  GD('GD'),

  /// Guadeloupe
  GP('GP'),

  /// Guam
  GU('GU'),

  /// Guatemala
  GT('GT'),

  /// Guernsey
  GG('GG'),

  /// Guinea
  GN('GN'),

  /// Guinea-Bissau
  GW('GW'),

  /// Guyana
  GY('GY'),

  /// Haiti
  HT('HT'),

  /// Heard Island and McDonald Islands
  HM('HM'),

  /// Holy See (Vatican City State)
  VA('VA'),

  /// Honduras
  HN('HN'),

  /// Hong Kong
  HK('HK'),

  /// Hungary
  HU('HU'),

  /// Iceland
  IS('IS'),

  /// India
  IN('IN'),

  /// Indonesia
  ID('ID'),

  /// Iran, Islamic Republic of
  IR('IR'),

  /// Iraq
  IQ('IQ'),

  /// Ireland
  IE('IE'),

  /// Isle of Man
  IM('IM'),

  /// Israel
  IL('IL'),

  /// Italy
  IT('IT'),

  /// Jamaica
  JM('JM'),

  /// Japan
  JP('JP'),

  /// Jersey
  JE('JE'),

  /// Jordan
  JO('JO'),

  /// Kazakhstan
  KZ('KZ'),

  /// Kenya
  KE('KE'),

  /// Kiribati
  KI('KI'),

  /// Korea, Democratic People's Republic of
  KP('KP'),

  /// Korea, Republic of
  KR('KR'),

  /// Kuwait
  KW('KW'),

  /// Kyrgyzstan
  KG('KG'),

  /// Lao People's Democratic Republic
  LA('LA'),

  /// Latvia
  LV('LV'),

  /// Lebanon
  LB('LB'),

  /// Lesotho
  LS('LS'),

  /// Liberia
  LR('LR'),

  /// Libya
  LY('LY'),

  /// Liechtenstein
  LI('LI'),

  /// Lithuania
  LT('LT'),

  /// Luxembourg
  LU('LU'),

  /// Macao
  MO('MO'),

  /// Macedonia, the Former Yugoslav Republic of
  MK('MK'),

  /// Madagascar
  MG('MG'),

  /// Malawi
  MW('MW'),

  /// Malaysia
  MY('MY'),

  /// Maldives
  MV('MV'),

  /// Mali
  ML('ML'),

  /// Malta
  MT('MT'),

  /// Marshall Islands
  MH('MH'),

  /// Martinique
  MQ('MQ'),

  /// Mauritania
  MR('MR'),

  /// Mauritius
  MU('MU'),

  /// Mayotte
  YT('YT'),

  /// Mexico
  MX('MX'),

  /// Micronesia, Federated States of
  FM('FM'),

  /// Moldova, Republic of
  MD('MD'),

  /// Monaco
  MC('MC'),

  /// Mongolia
  MN('MN'),

  /// Montenegro
  ME('ME'),

  /// Montserrat
  MS('MS'),

  /// Morocco
  MA('MA'),

  /// Mozambique
  MZ('MZ'),

  /// Myanmar
  MM('MM'),

  /// Namibia
  NA('NA'),

  /// Nauru
  NR('NR'),

  /// Nepal
  NP('NP'),

  /// Netherlands
  NL('NL'),

  /// New Caledonia
  NC('NC'),

  /// New Zealand
  NZ('NZ'),

  /// Nicaragua
  NI('NI'),

  /// Niger
  NE('NE'),

  /// Nigeria
  NG('NG'),

  /// Niue
  NU('NU'),

  /// Norfolk Island
  NF('NF'),

  /// Northern Mariana Islands
  MP('MP'),

  /// Norway
  NO('NO'),

  /// Oman
  OM('OM'),

  /// Pakistan
  PK('PK'),

  /// Palau
  PW('PW'),

  /// Palestine, State of
  PS('PS'),

  /// Panama
  PA('PA'),

  /// Papua New Guinea
  PG('PG'),

  /// Paraguay
  PY('PY'),

  /// Peru
  PE('PE'),

  /// Philippines
  PH('PH'),

  /// Pitcairn
  PN('PN'),

  /// Poland
  PL('PL'),

  /// Portugal
  PT('PT'),

  /// Puerto Rico
  PR('PR'),

  /// Qatar
  QA('QA'),

  /// Réunion
  RE('RE'),

  /// Romania
  RO('RO'),

  /// Russian Federation
  RU('RU'),

  /// Rwanda
  RW('RW'),

  /// Saint Barthélemy
  BL('BL'),

  /// Saint Helena, Ascension and Tristan da Cunha
  SH('SH'),

  /// Saint Kitts and Nevis
  KN('KN'),

  /// Saint Lucia
  LC('LC'),

  /// Saint Martin (French part)
  MF('MF'),

  /// Saint Pierre and Miquelon
  PM('PM'),

  /// Saint Vincent and the Grenadines
  VC('VC'),

  /// Samoa
  WS('WS'),

  /// San Marino
  SM('SM'),

  /// Sao Tome and Principe
  ST('ST'),

  /// Saudi Arabia
  SA('SA'),

  /// Senegal
  SN('SN'),

  /// Serbia
  RS('RS'),

  /// Seychelles
  SC('SC'),

  /// Sierra Leone
  SL('SL'),

  /// Singapore
  SG('SG'),

  /// Sint Maarten (Dutch part)
  SX('SX'),

  /// Slovakia
  SK('SK'),

  /// Slovenia
  SI('SI'),

  /// Solomon Islands
  SB('SB'),

  /// Somalia
  SO('SO'),

  /// South Africa
  ZA('ZA'),

  /// South Georgia and the South Sandwich Islands
  GS('GS'),

  /// South Sudan
  SS('SS'),

  /// Spain
  ES('ES'),

  /// Sri Lanka
  LK('LK'),

  /// Sudan
  SD('SD'),

  /// Suriname
  SR('SR'),

  /// Svalbard and Jan Mayen
  SJ('SJ'),

  /// Swaziland
  SZ('SZ'),

  /// Sweden
  SE('SE'),

  /// Switzerland
  CH('CH'),

  /// Syrian Arab Republic
  SY('SY'),

  /// Taiwan, Province of China
  TW('TW'),

  /// Tajikistan
  TJ('TJ'),

  /// Tanzania, United Republic of
  TZ('TZ'),

  /// Thailand
  TH('TH'),

  /// Timor-Leste
  TL('TL'),

  /// Togo
  TG('TG'),

  /// Tokelau
  TK('TK'),

  /// Tonga
  TO('TO'),

  /// Trinidad and Tobago
  TT('TT'),

  /// Tunisia
  TN('TN'),

  /// Turkey
  TR('TR'),

  /// Turkmenistan
  TM('TM'),

  /// Turks and Caicos Islands
  TC('TC'),

  /// Tuvalu
  TV('TV'),

  /// Uganda
  UG('UG'),

  /// Ukraine
  UA('UA'),

  /// United Arab Emirates
  AE('AE'),

  /// United Kingdom
  GB('GB'),

  /// United States
  US('US'),

  /// United States Minor Outlying Islands
  UM('UM'),

  /// Uruguay
  UY('UY'),

  /// Uzbekistan
  UZ('UZ'),

  /// Vanuatu
  VU('VU'),

  /// Venezuela, Bolivarian Republic of
  VE('VE'),

  /// Viet Nam
  VN('VN'),

  /// Virgin Islands, British
  VG('VG'),

  /// Virgin Islands, U.S.
  VI('VI'),

  /// Wallis and Futuna
  WF('WF'),

  /// Western Sahara
  EH('EH'),

  /// Yemen
  YE('YE'),

  /// Zambia
  ZM('ZM'),

  /// Zimbabwe
  ZW('ZW');

  final String _value;
  const Country(String value) : _value = value;
  String toJson() => _value;
}
