// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **화폐**
///
/// [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) 화폐 코드
///
/// 대한민국 원, 일본 엔이 아닌 화폐를 사용할 때에는 금액을 minor unit 단위로 입력해야 함에 유의하세요.
enum Currency {
  /// South Korean won
  KRW('KRW'),

  /// United States dollar
  USD('USD'),

  /// Euro
  EUR('EUR'),

  /// Japanese yen
  JPY('JPY'),

  /// Chinese yuan
  CNY('CNY'),

  /// Vietnamese dong
  VND('VND'),

  /// Thai baht
  THB('THB'),

  /// Singapore dollar
  SGD('SGD'),

  /// Australian dollar
  AUD('AUD'),

  /// Hong Kong dollar
  HKD('HKD'),

  /// United Arab Emirates dirham
  AED('AED'),

  /// Afghan afghani
  AFN('AFN'),

  /// Albanian lek
  ALL('ALL'),

  /// Armenian dram
  AMD('AMD'),

  /// Netherlands Antillean guilder
  ANG('ANG'),

  /// Angolan kwanza
  AOA('AOA'),

  /// Argentine peso
  ARS('ARS'),

  /// Aruban florin
  AWG('AWG'),

  /// Azerbaijani manat
  AZN('AZN'),

  /// Bosnia and Herzegovina convertible mark
  BAM('BAM'),

  /// Barbadian dollar
  BBD('BBD'),

  /// Bangladeshi taka
  BDT('BDT'),

  /// Bulgarian lev
  BGN('BGN'),

  /// Bermudian dollar
  BMD('BMD'),

  /// Brunei dollar
  BND('BND'),

  /// Boliviano
  BOB('BOB'),

  /// Bolivian Mvdol
  BOV('BOV'),

  /// Brazilian real
  BRL('BRL'),

  /// Bahamian dollar
  BSD('BSD'),

  /// Botswana pula
  BWP('BWP'),

  /// Belarusian ruble
  BYN('BYN'),

  /// Belize dollar
  BZD('BZD'),

  /// Canadian dollar
  CAD('CAD'),

  /// Congolese franc
  CDF('CDF'),

  /// WIR euro
  CHE('CHE'),

  /// Swiss franc
  CHF('CHF'),

  /// WIR franc
  CHW('CHW'),

  /// Chilean unit of account (UF)
  CLF('CLF'),

  /// Chilean peso
  CLP('CLP'),

  /// Colombian peso
  COP('COP'),

  /// Unidad de Valor Real
  COU('COU'),

  /// Costa Rican colon
  CRC('CRC'),

  /// Cuban convertible peso
  CUC('CUC'),

  /// Cuban peso
  CUP('CUP'),

  /// Cape Verdean escudo
  CVE('CVE'),

  /// Czech koruna
  CZK('CZK'),

  /// Djiboutian franc
  DJF('DJF'),

  /// Danish krone
  DKK('DKK'),

  /// Dominican peso
  DOP('DOP'),

  /// Algerian dinar
  DZD('DZD'),

  /// Egyptian pound
  EGP('EGP'),

  /// Eritrean nakfa
  ERN('ERN'),

  /// Ethiopian birr
  ETB('ETB'),

  /// Fiji dollar
  FJD('FJD'),

  /// Falkland Islands pound
  FKP('FKP'),

  /// Pound sterling
  GBP('GBP'),

  /// Georgian lari
  GEL('GEL'),

  /// Ghanaian cedi
  GHS('GHS'),

  /// Gibraltar pound
  GIP('GIP'),

  /// Gambian dalasi
  GMD('GMD'),

  /// Guinean franc
  GNF('GNF'),

  /// Guatemalan quetzal
  GTQ('GTQ'),

  /// Guyanese dollar
  GYD('GYD'),

  /// Honduran lempira
  HNL('HNL'),

  /// Croatian kuna
  HRK('HRK'),

  /// Haitian gourde
  HTG('HTG'),

  /// Hungarian forint
  HUF('HUF'),

  /// Indonesian rupiah
  IDR('IDR'),

  /// Israeli new shekel
  ILS('ILS'),

  /// Indian rupee
  INR('INR'),

  /// Iraqi dinar
  IQD('IQD'),

  /// Iranian rial
  IRR('IRR'),

  /// Icelandic króna
  ISK('ISK'),

  /// Jamaican dollar
  JMD('JMD'),

  /// Jordanian dinar
  JOD('JOD'),

  /// Kenyan shilling
  KES('KES'),

  /// Kyrgyzstani som
  KGS('KGS'),

  /// Cambodian riel
  KHR('KHR'),

  /// Comoro franc
  KMF('KMF'),

  /// North Korean won
  KPW('KPW'),

  /// Kuwaiti dinar
  KWD('KWD'),

  /// Cayman Islands dollar
  KYD('KYD'),

  /// Kazakhstani tenge
  KZT('KZT'),

  /// Lao kip
  LAK('LAK'),

  /// Lebanese pound
  LBP('LBP'),

  /// Sri Lankan rupee
  LKR('LKR'),

  /// Liberian dollar
  LRD('LRD'),

  /// Lesotho loti
  LSL('LSL'),

  /// Libyan dinar
  LYD('LYD'),

  /// Moroccan dirham
  MAD('MAD'),

  /// Moldovan leu
  MDL('MDL'),

  /// Malagasy ariary
  MGA('MGA'),

  /// Macedonian denar
  MKD('MKD'),

  /// Myanmar kyat
  MMK('MMK'),

  /// Mongolian tögrög
  MNT('MNT'),

  /// Macanese pataca
  MOP('MOP'),

  /// Mauritanian ouguiya
  MRU('MRU'),

  /// Mauritian rupee
  MUR('MUR'),

  /// Maldivian rufiyaa
  MVR('MVR'),

  /// Malawian kwacha
  MWK('MWK'),

  /// Mexican peso
  MXN('MXN'),

  /// Mexican Unidad de Inversion
  MXV('MXV'),

  /// Mozambican metical
  MZN('MZN'),

  /// Namibian dollar
  NAD('NAD'),

  /// Nigerian naira
  NGN('NGN'),

  /// Nicaraguan córdoba
  NIO('NIO'),

  /// Norwegian krone
  NOK('NOK'),

  /// Nepalese rupee
  NPR('NPR'),

  /// New Zealand dollar
  NZD('NZD'),

  /// Omani rial
  OMR('OMR'),

  /// Panamanian balboa
  PAB('PAB'),

  /// Peruvian sol
  PEN('PEN'),

  /// Papua New Guinean kina
  PGK('PGK'),

  /// Philippine peso
  PHP('PHP'),

  /// Pakistani rupee
  PKR('PKR'),

  /// Polish złoty
  PLN('PLN'),

  /// Paraguayan guaraní
  PYG('PYG'),

  /// Qatari riyal
  QAR('QAR'),

  /// Romanian leu
  RON('RON'),

  /// Serbian dinar
  RSD('RSD'),

  /// Russian ruble
  RUB('RUB'),

  /// Rwandan franc
  RWF('RWF'),

  /// Saudi riyal
  SAR('SAR'),

  /// Solomon Islands dollar
  SBD('SBD'),

  /// Seychelles rupee
  SCR('SCR'),

  /// Sudanese pound
  SDG('SDG'),

  /// Swedish krona
  SEK('SEK'),

  /// Saint Helena pound
  SHP('SHP'),

  /// Sierra Leonean leone (new leone)
  SLE('SLE'),

  /// Sierra Leonean leone (old leone)
  SLL('SLL'),

  /// Somali shilling
  SOS('SOS'),

  /// Surinamese dollar
  SRD('SRD'),

  /// South Sudanese pound
  SSP('SSP'),

  /// São Tomé and Príncipe dobra
  STN('STN'),

  /// Salvadoran colón
  SVC('SVC'),

  /// Syrian pound
  SYP('SYP'),

  /// Swazi lilangeni
  SZL('SZL'),

  /// Tajikistani somoni
  TJS('TJS'),

  /// Turkmenistan manat
  TMT('TMT'),

  /// Tunisian dinar
  TND('TND'),

  /// Tongan paʻanga
  TOP('TOP'),

  /// Turkish lira
  TRY('TRY'),

  /// Trinidad and Tobago dollar
  TTD('TTD'),

  /// New Taiwan dollar
  TWD('TWD'),

  /// Tanzanian shilling
  TZS('TZS'),

  /// Ukrainian hryvnia
  UAH('UAH'),

  /// Ugandan shilling
  UGX('UGX'),

  /// United States dollar (next day)
  USN('USN'),

  /// Uruguay Peso en Unidades Indexadas
  UYI('UYI'),

  /// Uruguayan peso
  UYU('UYU'),

  /// Unidad previsional
  UYW('UYW'),

  /// Uzbekistan som
  UZS('UZS'),

  /// Venezuelan bolívar digital
  VED('VED'),

  /// Venezuelan bolívar soberano
  VES('VES'),

  /// Vanuatu vatu
  VUV('VUV'),

  /// Samoan tala
  WST('WST'),

  /// CFA franc BEAC
  XAF('XAF'),

  /// Silver (one troy ounce)
  XAG('XAG'),

  /// Gold (one troy ounce)
  XAU('XAU'),

  /// European Composite Unit
  XBA('XBA'),

  /// European Monetary Unit
  XBB('XBB'),

  /// European Unit of Account 9
  XBC('XBC'),

  /// European Unit of Account 17
  XBD('XBD'),

  /// East Caribbean dollar
  XCD('XCD'),

  /// Special drawing rights
  XDR('XDR'),

  /// CFA franc BCEAO
  XOF('XOF'),

  /// Palladium (one troy ounce)
  XPD('XPD'),

  /// CFP franc
  XPF('XPF'),

  /// Platinum (one troy ounce)
  XPT('XPT'),

  /// SUCRE
  XSU('XSU'),

  /// Code reserved for testing
  XTS('XTS'),

  /// ADB Unit of Account
  XUA('XUA'),

  /// No currency
  XXX('XXX'),

  /// Yemeni rial
  YER('YER'),

  /// South African rand
  ZAR('ZAR'),

  /// Zambian kwacha
  ZMW('ZMW'),

  /// Zimbabwean dollar
  ZWL('ZWL');

  final String _value;
  const Currency(String value) : _value = value;
  String toJson() => _value;
}
