// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/address.dart';
import 'package:portone_flutter/v2/model/entity/gender.dart';

class Customer {
  /// **구매자 ID**
  ///
  /// 스마트로, KG이니시스 SBPS 일본결제, Triple-A에서 사용합니다.
  ///
  /// 토스페이먼츠와 스마트로의 빌링키 발급에서 사용합니다.
  final String? customerId;

  /// **구매자 전체 이름**
  ///
  /// `fullName`이 사용되는 PG에서 `fullName`이 없고 `firstName`과 `lastName`이 있는 경우 `${lastName} ${firstName}`이 대신 사용됩니다.
  final String? fullName;

  /// **구매자 성이 아닌 이름**
  ///
  /// 페이팔에서 구매자 페이팔 계정 소유자의 이름을 지정합니다.
  final String? firstName;

  /// **구매자 성**
  ///
  /// 페이팔에서 구매자 페이팔 계정 소유자의 성을 지정합니다.
  final String? lastName;

  /// **구매자 휴대전화 번호**
  final String? phoneNumber;

  /// **구매자 이메일 주소**
  ///
  /// 올바른 형식의 이메일 주소여야 합니다.
  final String? email;

  /// **주소 정보**
  final Address? address;

  /// **구매자 우편번호**
  final String? zipcode;

  /// 구매자 성별
  final Gender? gender;

  /// **구매자 출생년도**
  ///
  /// `"1990"`과 같은 형식입니다.
  ///
  /// KG이니시스 통합인증에서 `flgFixedUser`가 `Y`인 경우 필수입니다.
  final String? birthYear;

  /// **구매자 출생월**
  ///
  /// `"12"`, `"07"`과 같은 형식입니다.
  ///
  /// KG이니시스 통합인증에서 `flgFixedUser`가 `Y`인 경우 필수입니다.
  final String? birthMonth;

  /// **구매자 출생일**
  ///
  /// `"25"`, `"08"`과 같은 형식입니다.
  ///
  /// KG이니시스 통합인증에서 `flgFixedUser`가 `Y`인 경우 필수입니다.
  final String? birthDay;

  /// **구매자 일본어 성이 아닌 이름 후리가나(읽는 법)**
  ///
  /// KG이니시스 JPPG 일본 편의점 결제에서 필수입니다. 최대 20바이트입니다.
  final String? firstNameKana;

  /// **구매자 일본어 성 후리가나(읽는 법)**
  ///
  /// KG이니시스 JPPG 일본 편의점 결제에서 필수입니다. 최대 20바이트입니다.
  final String? lastNameKana;

  Customer({
    this.customerId,
    this.fullName,
    this.firstName,
    this.lastName,
    this.phoneNumber,
    this.email,
    this.address,
    this.zipcode,
    this.gender,
    this.birthYear,
    this.birthMonth,
    this.birthDay,
    this.firstNameKana,
    this.lastNameKana,
  });

  Map<String, dynamic> toJson() => {
    if (customerId != null) 'customerId': customerId!,
    if (fullName != null) 'fullName': fullName!,
    if (firstName != null) 'firstName': firstName!,
    if (lastName != null) 'lastName': lastName!,
    if (phoneNumber != null) 'phoneNumber': phoneNumber!,
    if (email != null) 'email': email!,
    if (address != null) 'address': address!.toJson(),
    if (zipcode != null) 'zipcode': zipcode!,
    if (gender != null) 'gender': gender!.toJson(),
    if (birthYear != null) 'birthYear': birthYear!,
    if (birthMonth != null) 'birthMonth': birthMonth!,
    if (birthDay != null) 'birthDay': birthDay!,
    if (firstNameKana != null) 'firstNameKana': firstNameKana!,
    if (lastNameKana != null) 'lastNameKana': lastNameKana!,
  };
}
