// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// PG 제휴로 간편결제를 이용할 때, 간편결제 UI를 직접 호출할 수 있는 간편결제
enum EasyPayProvider {
  /// 네이버페이
  ///
  /// - 토스페이먼츠
  /// - 나이스페이먼츠
  /// - KG이니시스
  /// - 스마트로
  /// - NHN KCP
  /// - KSNET
  /// - 한국결제네트웍스
  NAVERPAY('NAVERPAY'),

  /// 카카오페이
  ///
  /// - 토스페이먼츠
  /// - 나이스페이먼츠
  /// - KG이니시스
  /// - 스마트로
  /// - NHN KCP
  /// - KSNET
  /// - 한국결제네트웍스
  /// - 웰컴페이먼츠
  KAKAOPAY('KAKAOPAY'),

  /// 토스페이
  ///
  /// - 토스페이먼츠
  /// - KG이니시스
  /// - NHN KCP
  /// - 스마트로
  /// - 한국결제네트웍스
  /// - 웰컴페이먼츠
  TOSSPAY('TOSSPAY'),

  /// 페이코
  ///
  /// - 토스페이먼츠
  /// - 나이스페이먼츠
  /// - KG이니시스
  /// - 스마트로
  /// - KSNET
  /// - 한국결제네트웍스
  /// - 웰컴페이먼츠
  PAYCO('PAYCO'),

  /// 차이페이
  CHAI('CHAI'),

  /// L페이
  ///
  /// - 토스페이먼츠
  /// - 나이스페이먼츠
  /// - KG이니시스
  /// - 스마트로
  /// - KSNET
  /// - 웰컴페이먼츠
  LPAY('LPAY'),

  /// K페이
  KPAY('KPAY'),

  /// SSG페이
  ///
  /// - 토스페이먼츠
  /// - 나이스페이먼츠
  /// - KG이니시스
  /// - NHN KCP
  /// - KSNET
  SSGPAY('SSGPAY'),

  /// 삼성페이
  ///
  /// - 토스페이먼츠
  /// - 나이스페이먼츠
  /// - KG이니시스
  /// - NHN KCP
  /// - 스마트로
  /// - 한국결제네트웍스
  SAMSUNGPAY('SAMSUNGPAY'),

  /// 애플페이
  ///
  /// - 토스페이먼츠
  /// - 나이스페이먼츠
  /// - KG이니시스
  /// - NHN KCP
  APPLEPAY('APPLEPAY'),

  /// LG페이
  ///
  /// - 토스페이먼츠
  LGPAY('LGPAY'),

  /// SK페이
  ///
  /// - 나이스페이먼츠
  SKPAY('SKPAY'),

  /// 핀페이
  ///
  /// - 스마트로
  PINPAY('PINPAY'),

  /// 토스 브랜드페이
  TOSS_BRANDPAY('TOSS_BRANDPAY'),

  /// 하이픈
  HYPHEN('HYPHEN'),

  /// 라인페이
  ///
  /// - 스마트로
  LINEPAY('LINEPAY'),

  /// 티머니
  ///
  /// - 스마트로
  TMONEY('TMONEY'),

  /// PayPay
  ///
  /// - KG이니시스 JPPG/SBPS 일본결제
  PAYPAY('PAYPAY'),

  /// 아마존페이
  ///
  /// - KG이니시스 JPPG 일본결제
  AMAZONPAY('AMAZONPAY'),

  /// 라쿠텐페이
  ///
  /// - KG이니시스 JPPG 일본결제
  RAKUTENPAY('RAKUTENPAY'),

  /// dBarai
  ///
  /// - KG이니시스 JPPG 일본결제
  DBARAI('DBARAI'),

  /// auPAY
  ///
  /// - KG이니시스 JPPG 일본결제
  AUPAY('AUPAY'),

  /// Merpay
  ///
  /// - KG이니시스 JPPG 일본결제
  MERPAY('MERPAY');

  final String _value;
  const EasyPayProvider(String value) : _value = value;
  String toJson() => _value;
  static EasyPayProvider fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
