// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 간편결제 결제수단
enum EasyPayPaymentMethod {
  /// 카드
  CARD('CARD'),

  /// 포인트(충전, 적립) 결제
  CHARGE('CHARGE'),

  /// 계좌결제
  TRANSFER('TRANSFER'),

  /// 포인트 및 계좌결제가 모두 가능한 경우
  MONEY('MONEY');

  final String _value;
  const EasyPayPaymentMethod(String value) : _value = value;
  String toJson() => _value;
  static EasyPayPaymentMethod fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
