// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **무이자 할부를 적용할 PG사 구분코드**
enum FreeInstallmentPlanPgProvider {
  INICIS_V2('INICIS_V2'),
  KCP_V2('KCP_V2'),
  KSNET('KSNET'),
  NICE_V2('NICE_V2'),
  TOSSPAYMENTS('TOSSPAYMENTS'),
  WELCOME('WELCOME');

  final String _value;
  const FreeInstallmentPlanPgProvider(String value) : _value = value;
  String toJson() => _value;
}
