// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 구매자 성별
enum Gender {
  /// 남성
  MALE('MALE'),

  /// 여성
  FEMALE('FEMALE'),

  /// 기타
  OTHER('OTHER');

  final String _value;
  const Gender(String value) : _value = value;
  String toJson() => _value;
}
