// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **상품권 종류**
enum GiftCertificateType {
  /// 도서문화상품권
  /// | KG이니시스
  BOOKNLIFE('BOOKNLIFE'),

  /// 스마트문상, (구)게임문화상품권
  SMART_MUNSANG('SMART_MUNSANG'),

  /// 컬쳐랜드 문화상품권
  CULTURELAND('CULTURELAND'),

  /// 문화상품권
  CULTURE_GIFT('CULTURE_GIFT');

  final String _value;
  const GiftCertificateType(String value) : _value = value;
  String toJson() => _value;
  static GiftCertificateType fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
