// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **결제창이 iframe 방식일 경우 결제창에 적용할 속성**
class Iframe {
  /// `false`로 설정하면 결제창 배경이 투명해집니다.
  final bool? dim;

  Iframe({this.dim});

  Map<String, dynamic> toJson() => {if (dim != null) 'dim': dim!};

  static Iframe fromJson(Map<String, dynamic> json) =>
      Iframe(dim: json['dim'] as bool?);
}
