// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/loadable_ui_type.dart';

enum IssueBillingKeyUIType {
  PAYPAL_RT('PAYPAL_RT');

  final String _value;
  const IssueBillingKeyUIType(String value) : _value = value;
  String toJson() => _value;
  static IssueBillingKeyUIType fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
  LoadableUIType toLoadableUIType() =>
      LoadableUITypeIssueBillingKeyUiType(this);
}
