// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/issue_billing_key_ui_type.dart';
import 'package:portone_flutter/v2/model/entity/payment_ui_type.dart';

sealed class LoadableUIType {
  dynamic toJson();
}

class LoadableUITypePaymentUiType extends LoadableUIType {
  final PaymentUIType value;
  LoadableUITypePaymentUiType(this.value);
  @override
  dynamic toJson() => value.toJson();
}

class LoadableUITypeIssueBillingKeyUiType extends LoadableUIType {
  final IssueBillingKeyUIType value;
  LoadableUITypeIssueBillingKeyUiType(this.value);
  @override
  dynamic toJson() => value.toJson();
}
