// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **UI 언어**
///
/// KG이니시스, 스마트로, KSNET, 웰컴페이먼츠 (PC), 한국결제네트웍스, 엑심베이, Triple-A에서 설정 가능하며, PG마다 지원하는 언어 목록은 차이가 있습니다.
enum Locale {
  /// 한국어
  ///
  /// - KG이니시스
  /// - 스마트로
  /// - KSNET
  /// - 웰컴페이먼츠 (PC)
  /// - 한국결제네트웍스
  /// - 엑심베이
  KO_KR('KO_KR'),

  /// 영어
  ///
  /// - KG이니시스
  /// - 스마트로
  /// - KSNET
  /// - 웰컴페이먼츠 (PC)
  /// - 한국결제네트웍스
  /// - 엑심베이
  /// - Triple-A
  EN_US('EN_US'),

  /// 중국어 (중국 본토)
  ///
  /// - KG이니시스 (PC)
  /// - 웰컴페이먼츠 (PC)
  /// - 엑심베이
  /// - Triple-A
  ZH_CN('ZH_CN'),

  /// 중국어 (대만)
  ///
  /// - 엑심베이
  /// - Triple-A
  ZH_TW('ZH_TW'),

  /// 일본어
  ///
  /// - 엑심베이
  /// - Triple-A
  JA_JP('JA_JP'),

  /// 러시아어
  ///
  /// - 엑심베이
  /// - Triple-A
  RU_RU('RU_RU'),

  /// 타이어
  ///
  /// - 엑심베이
  TH_TH('TH_TH'),

  /// 베트남어
  ///
  /// - 엑심베이
  VI_VN('VI_VN'),

  /// 인도네시아어
  ///
  /// - Triple-A
  ID_ID('ID_ID'),

  /// 프랑스어
  ///
  /// - Triple-A
  FR_FR('FR_FR'),

  /// 네덜란드어
  ///
  /// - Triple-A
  NL_NL('NL_NL'),

  /// 에스파냐어
  ///
  /// - Triple-A
  ES_ES('ES_ES'),

  /// 포르투갈어
  ///
  /// - Triple-A
  PT_PT('PT_PT'),

  /// 독일어
  ///
  /// - Triple-A
  DE_DE('DE_DE'),

  /// 이탈리아어
  ///
  /// - Triple-A
  IT_IT('IT_IT'),

  /// 폴란드어
  ///
  /// - Triple-A
  PL_PL('PL_PL'),

  /// 현대 표준 아랍어
  ///
  /// - Triple-A
  AR_001('AR_001');

  final String _value;
  const Locale(String value) : _value = value;
  String toJson() => _value;
}
