// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **UI 언어**
///
/// KG이니시스, 스마트로, KSNET, 웰컴페이먼츠 (PC), 한국결제네트웍스, 엑심베이, Triple-A, 페이먼트월에서 설정 가능하며, PG마다 지원하는 언어 목록은 차이가 있습니다.
enum Locale {
  /// 한국어
  ///
  /// - KG이니시스
  /// - 스마트로
  /// - KSNET
  /// - 웰컴페이먼츠 (PC)
  /// - 한국결제네트웍스
  /// - 엑심베이
  /// - 페이먼트월
  KO_KR('KO_KR'),

  /// 영어
  ///
  /// - KG이니시스
  /// - 스마트로
  /// - KSNET
  /// - 웰컴페이먼츠 (PC)
  /// - 한국결제네트웍스
  /// - 엑심베이
  /// - Triple-A
  /// - 페이먼트월
  EN_US('EN_US'),

  /// 중국어 (중국 본토)
  ///
  /// - KG이니시스 (PC)
  /// - 웰컴페이먼츠 (PC)
  /// - 엑심베이
  /// - Triple-A
  /// - 페이먼트월
  ZH_CN('ZH_CN'),

  /// 중국어 (대만)
  ///
  /// - 엑심베이
  /// - Triple-A
  /// - 페이먼트월
  ZH_TW('ZH_TW'),

  /// 일본어
  ///
  /// - 엑심베이
  /// - Triple-A
  /// - 페이먼트월
  JA_JP('JA_JP'),

  /// 러시아어
  ///
  /// - 엑심베이
  /// - Triple-A
  /// - 페이먼트월
  RU_RU('RU_RU'),

  /// 타이어
  ///
  /// - 엑심베이
  /// - 페이먼트월
  TH_TH('TH_TH'),

  /// 베트남어
  ///
  /// - 엑심베이
  /// - 페이먼트월
  VI_VN('VI_VN'),

  /// 인도네시아어
  ///
  /// - Triple-A
  ID_ID('ID_ID'),

  /// 프랑스어
  ///
  /// - Triple-A
  /// - 페이먼트월
  FR_FR('FR_FR'),

  /// 네덜란드어
  ///
  /// - Triple-A
  /// - 페이먼트월
  NL_NL('NL_NL'),

  /// 에스파냐어
  ///
  /// - Triple-A
  /// - 페이먼트월
  ES_ES('ES_ES'),

  /// 포르투갈어
  ///
  /// - Triple-A
  /// - 페이먼트월
  PT_PT('PT_PT'),

  /// 독일어
  ///
  /// - Triple-A
  /// - 페이먼트월
  DE_DE('DE_DE'),

  /// 이탈리아어
  ///
  /// - Triple-A
  /// - 페이먼트월
  IT_IT('IT_IT'),

  /// 폴란드어
  ///
  /// - Triple-A
  /// - 페이먼트월
  PL_PL('PL_PL'),

  /// 현대 표준 아랍어
  ///
  /// - Triple-A
  AR_001('AR_001'),

  /// 튀르키예어
  ///
  /// - 페이먼트월
  TR_TR('TR_TR'),

  /// 스웨덴어
  ///
  /// - 페이먼트월
  SV_SE('SV_SE'),

  /// 핀란드어
  ///
  /// - 페이먼트월
  FI_FI('FI_FI'),

  /// 우크라이나어
  ///
  /// - 페이먼트월
  UK_UA('UK_UA'),

  /// 그리스어
  ///
  /// - 페이먼트월
  EL_GR('EL_GR'),

  /// 타갈로그어
  ///
  /// - 페이먼트월
  TL_PH('TL_PH'),

  /// 힌디어
  ///
  /// - 페이먼트월
  HI_IN('HI_IN'),

  /// 크로아티아어
  ///
  /// - 페이먼트월
  HR_HR('HR_HR'),

  /// 리투아니아어
  ///
  /// - 페이먼트월
  LT_LT('LT_LT'),

  /// 슬로베니아어
  ///
  /// - 페이먼트월
  SL_SI('SL_SI'),

  /// 세르비아어
  ///
  /// - 페이먼트월
  SR_RS('SR_RS'),

  /// 불가리아어
  ///
  /// - 페이먼트월
  BG_BG('BG_BG'),

  /// 포르투갈어 (브라질)
  ///
  /// - 페이먼트월
  PT_BR('PT_BR');

  final String _value;
  const Locale(String value) : _value = value;
  String toJson() => _value;
}
