// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/offer_period_range.dart';

/// **종료 지점만 있는 기간 범위**
class OfferPeriodRangeTo {
  /// **종료 지점**
  final String to;

  OfferPeriodRangeTo({required this.to});

  Map<String, dynamic> toJson() => {'to': to};

  OfferPeriodRange toOfferPeriodRange() =>
      OfferPeriodRangeOfferPeriodRangeTo(this);
}
