// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/offer_period_range.dart';

/// **시작 지점과 종료 지점이 모두 있는 기간 범위**
class OfferPeriodRangeFromTo {
  /// **시작 시점**
  final String from;

  /// **종료 지점**
  final String to;

  OfferPeriodRangeFromTo({required this.from, required this.to});

  Map<String, dynamic> toJson() => {'from': from, 'to': to};

  static OfferPeriodRangeFromTo fromJson(Map<String, dynamic> json) =>
      OfferPeriodRangeFromTo(
        from: json['from'] as String,
        to: json['to'] as String,
      );

  OfferPeriodRange toOfferPeriodRange() =>
      OfferPeriodRangeOfferPeriodRangeFromTo(this);
}
