// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/offer_period_range.dart';

/// **시작 시점만 있는 기간 범위**
class OfferPeriodRangeFrom {
  /// **시작 시점**
  final String from;

  OfferPeriodRangeFrom({required this.from});

  Map<String, dynamic> toJson() => {'from': from};

  static OfferPeriodRangeFrom fromJson(Map<String, dynamic> json) =>
      OfferPeriodRangeFrom(from: json['from'] as String);

  OfferPeriodRange toOfferPeriodRange() =>
      OfferPeriodRangeOfferPeriodRangeFrom(this);
}
