// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/offer_period_range.dart'
    as _offer_period_range;

/// **서비스 제공 기간**
///
/// range와 interval 중 하나를 입력해주세요.
///
/// - range: 제공 기간 범위
/// - interval: 제공 기간 주기
///
/// 예1) 2023년 1월 1일 00시 00분 00초(KST) ~
///
/// ```js
/// range: {
/// from: '2023-01-01T00:00:00+09:00'
/// }
/// ```
///
/// 예2) ~ 2023년 1월 1일 00시 00분 00초(KST)
///
/// ```js
/// range: {
/// to: '2023-01-01T00:00:00+09:00'
/// }
/// ```
///
/// 예3) 2023년 1월 1일 00시 00분 00초(KST) ~ 2023년 12월 31일 23시 59분 59초(KST)
///
/// ```js
/// range: {
/// from: '2023-12-31T23:59:59+09:00'
/// to: '2023-01-01T00:00:00+09:00'
/// }
/// ```
///
/// 예4) 30일 주기
/// `interval: '30d'`
///
/// 예5) 6개월 주기
/// `interval: '6m'`
///
/// 예6) 1년 주기
/// `interval: '1y'`
sealed class OfferPeriod {
  Map<String, dynamic> toJson();
}

/// **기간 범위**
class OfferPeriodRange extends OfferPeriod {
  final _offer_period_range.OfferPeriodRange? range;
  OfferPeriodRange(this.range);
  @override
  Map<String, dynamic> toJson() => {'range': range?.toJson()};
}

/// **제공 주기**
///
/// 제공 주기 (`${number}d | ${number}m | ${number}y` 형태로 입력할 수 있습니다.)
class OfferPeriodInterval extends OfferPeriod {
  final String? interval;
  OfferPeriodInterval(this.interval);
  @override
  Map<String, dynamic> toJson() => {'interval': interval};
}
