// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/offer_period_range_from.dart';
import 'package:portone_flutter/v2/model/entity/offer_period_range_from_to.dart';
import 'package:portone_flutter/v2/model/entity/offer_period_range_to.dart';

/// **기간 범위**
sealed class OfferPeriodRange {
  dynamic toJson();
}

class OfferPeriodRangeOfferPeriodRangeFrom extends OfferPeriodRange {
  final OfferPeriodRangeFrom value;
  OfferPeriodRangeOfferPeriodRangeFrom(this.value);
  @override
  dynamic toJson() => value.toJson();
}

class OfferPeriodRangeOfferPeriodRangeTo extends OfferPeriodRange {
  final OfferPeriodRangeTo value;
  OfferPeriodRangeOfferPeriodRangeTo(this.value);
  @override
  dynamic toJson() => value.toJson();
}

class OfferPeriodRangeOfferPeriodRangeFromTo extends OfferPeriodRange {
  final OfferPeriodRangeFromTo value;
  OfferPeriodRangeOfferPeriodRangeFromTo(this.value);
  @override
  dynamic toJson() => value.toJson();
}
