// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/loadable_ui_type.dart';

enum PaymentUIType {
  PAYPAL_SPB('PAYPAL_SPB');

  final String _value;
  const PaymentUIType(String value) : _value = value;
  String toJson() => _value;
  static PaymentUIType fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
  LoadableUIType toLoadableUIType() => LoadableUITypePaymentUiType(this);
}
