// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **구매 상품 상세 정보**
class Product {
  /// **상품 ID**
  final String id;

  /// **상품명**
  final String name;

  /// **상품 코드**
  final String? code;

  /// **상품 단위 가격**
  ///
  /// 상품의 단위당 가격을 정수로 나타냅니다.
  ///
  /// 해외 통화의 경우 통화의 최소 단위(minor unit)를 기준으로 합니다. 예를 들어, USD의 최소 단위는 센트(0.01 USD)이므로, 6 USD의 경우 100배하여 600으로 입력합니다.
  ///
  /// 최소 단위는 [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)에 표준화된 것을 기준으로 합니다.
  ///
  /// - KRW: 1배
  /// - USD: 100배
  /// - JPY: 1배
  final int amount;

  /// **상품 수량**
  final int quantity;

  /// **상품 태그**
  final String? tag;

  /// **상품 판매 URL**
  final String? link;

  /// **상품 설명**
  final String? description;

  Product({
    required this.id,
    required this.name,
    this.code,
    required this.amount,
    required this.quantity,
    this.tag,
    this.link,
    this.description,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    if (code != null) 'code': code!,
    'amount': amount,
    'quantity': quantity,
    if (tag != null) 'tag': tag!,
    if (link != null) 'link': link!,
    if (description != null) 'description': description!,
  };
}
