// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **상품 유형**
enum ProductType {
  /// 실물
  REAL('REAL'),

  /// 디지털
  DIGITAL('DIGITAL');

  final String _value;
  const ProductType(String value) : _value = value;
  String toJson() => _value;
}
