// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 상점 영업시간 (HH:mm)
class StoreDetailsOpeningHours {
  /// 영업 시작 시간
  final String? open;

  /// 영업 종료 시간
  final String? close;

  StoreDetailsOpeningHours({this.open, this.close});

  Map<String, dynamic> toJson() => {
    if (open != null) 'open': open!,
    if (close != null) 'close': close!,
  };

  static StoreDetailsOpeningHours fromJson(Map<String, dynamic> json) =>
      StoreDetailsOpeningHours(
        open: json['open'] as String?,
        close: json['close'] as String?,
      );
}
