// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/store_details_opening_hours.dart';

/// **상점 정보**
///
/// - KSNET 카카오페이의 경우 필수 입력
/// - 나이스페이먼츠의 경우 매출 전표에 표기 할 용도로 선택 입력
/// - KG이니시스 일본결제의 경우 JPPG(gmoPayment) 결제의 상점정보로 사용되거나 편의점 결제 시 영수증 표시 정보로 사용됨.
class StoreDetails {
  /// **대표자 이름**
  final String? ceoFullName;

  /// **전화번호**
  final String? phoneNumber;

  /// **주소**
  final String? address;

  /// 우편번호
  final String? zipcode;

  /// 이메일
  final String? email;

  /// **사업자명 (상호)**
  final String? businessName;

  /// **사업자 등록 번호**
  final String? businessRegistrationNumber;

  /// **상점명**
  final String? storeName;

  /// 상점명 약어
  final String? storeNameShort;

  /// 상점명 영문
  final String? storeNameEn;

  /// 상점명 후리카나 (일본어 읽는법 표기)
  final String? storeNameKana;

  /// 상점 영업시간 (HH:mm)
  final StoreDetailsOpeningHours? openingHours;

  /// **상점 연락처 정보 이름**
  ///
  /// ex: 문의창구, 연락처, 지원창구
  final String? contactName;

  StoreDetails({
    this.ceoFullName,
    this.phoneNumber,
    this.address,
    this.zipcode,
    this.email,
    this.businessName,
    this.businessRegistrationNumber,
    this.storeName,
    this.storeNameShort,
    this.storeNameEn,
    this.storeNameKana,
    this.openingHours,
    this.contactName,
  });

  Map<String, dynamic> toJson() => {
    if (ceoFullName != null) 'ceoFullName': ceoFullName!,
    if (phoneNumber != null) 'phoneNumber': phoneNumber!,
    if (address != null) 'address': address!,
    if (zipcode != null) 'zipcode': zipcode!,
    if (email != null) 'email': email!,
    if (businessName != null) 'businessName': businessName!,
    if (businessRegistrationNumber != null)
      'businessRegistrationNumber': businessRegistrationNumber!,
    if (storeName != null) 'storeName': storeName!,
    if (storeNameShort != null) 'storeNameShort': storeNameShort!,
    if (storeNameEn != null) 'storeNameEn': storeNameEn!,
    if (storeNameKana != null) 'storeNameKana': storeNameKana!,
    if (openingHours != null) 'openingHours': openingHours!.toJson(),
    if (contactName != null) 'contactName': contactName!,
  };
}
