// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **트랜잭션 유형**
///
/// - PAYMENT: 결제
/// - ISSUE\_BILLING\_KEY: 빌링키 발급
/// - IDENTITY\_VERIFICATION: 본인 인증
/// - ISSUE\_BILLING\_KEY\_AND\_PAY: 빌링키 발급과 동시에 결제
enum TransactionType {
  /// 결제
  PAYMENT('PAYMENT'),

  /// 빌링키 발급
  ISSUE_BILLING_KEY('ISSUE_BILLING_KEY'),

  /// 본인 인증
  IDENTITY_VERIFICATION('IDENTITY_VERIFICATION'),

  /// 빌링키 발급 및 초회결제
  ISSUE_BILLING_KEY_AND_PAY('ISSUE_BILLING_KEY_AND_PAY');

  final String _value;
  const TransactionType(String value) : _value = value;
  String toJson() => _value;
  static TransactionType fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
