// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/window_type.dart';

/// **환경 별 제공되는 결제/본인인증 창 유형**
///
/// - PG사에 따라 가능한 창 유형이 다릅니다.
/// - 전달되지 않았을 때 결정되는 기본 창이 다릅니다.
/// - 미입력 시, 해당 PG사의 기본 창 방식을 따릅니다.
class WindowTypes {
  final WindowType? pc;
  final WindowType? mobile;

  WindowTypes({this.pc, this.mobile});

  Map<String, dynamic> toJson() => {
    if (pc != null) 'pc': pc!.toJson(),
    if (mobile != null) 'mobile': mobile!.toJson(),
  };

  static WindowTypes fromJson(Map<String, dynamic> json) => WindowTypes(
    pc: json['pc'] != null ? WindowType.fromJson(json['pc']) : null,
    mobile: json['mobile'] != null ? WindowType.fromJson(json['mobile']) : null,
  );
}
