// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

enum WindowType {
  IFRAME('IFRAME'),
  POPUP('POPUP'),
  REDIRECTION('REDIRECTION'),
  UI('UI');

  final String _value;
  const WindowType(String value) : _value = value;
  String toJson() => _value;
}
