// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

enum WindowType {
  IFRAME('IFRAME'),
  POPUP('POPUP'),
  REDIRECTION('REDIRECTION'),
  UI('UI');

  final String _value;
  const WindowType(String value) : _value = value;
  String toJson() => _value;
  static WindowType fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
