// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 개인/법인카드 선택 옵션
enum InicisV2CardUse {
  /// 개인카드만 선택 가능
  percard('percard'),

  /// 법인 카드만 선택 가능
  cocard('cocard');

  final String _value;
  const InicisV2CardUse(String value) : _value = value;
  String toJson() => _value;
}
