// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/inicis_v_2_card_use.dart';

/// **KG이니시스 bypass 파라미터**
class InicisV2IssueBillingKeyBypass {
  /// 개인/법인카드 선택 옵션
  final InicisV2CardUse? carduse;

  InicisV2IssueBillingKeyBypass({this.carduse});

  Map<String, dynamic> toJson() => {
    if (carduse != null) 'carduse': carduse!.toJson(),
  };

  static InicisV2IssueBillingKeyBypass fromJson(Map<String, dynamic> json) =>
      InicisV2IssueBillingKeyBypass(
        carduse:
            json['carduse'] != null
                ? InicisV2CardUse.fromJson(json['carduse'])
                : null,
      );
}
