// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 결제창에서 주민번호/사업자 번호 고정여부 설정
enum KcpV2BatchSocChoice {
  /// 주민번호만 표시
  S('S'),

  /// 사업자번호만 표시
  C('C');

  final String _value;
  const KcpV2BatchSocChoice(String value) : _value = value;
  String toJson() => _value;
}
