// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/kcp_v_2_batch_soc_choice.dart';

/// **KCP bypass 파라미터**
class KcpV2IssueBillingKeyBypass {
  /// 결제창에서 주민번호/사업자 번호 고정여부 설정
  final KcpV2BatchSocChoice? batchSocChoice;

  KcpV2IssueBillingKeyBypass({this.batchSocChoice});

  Map<String, dynamic> toJson() => {
    if (batchSocChoice != null) 'batch_soc_choice': batchSocChoice!.toJson(),
  };

  static KcpV2IssueBillingKeyBypass fromJson(Map<String, dynamic> json) =>
      KcpV2IssueBillingKeyBypass(
        batchSocChoice:
            json['batch_soc_choice'] != null
                ? KcpV2BatchSocChoice.fromJson(json['batch_soc_choice'])
                : null,
      );
}
