// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **네이버페이 bypass 파라미터**
class NaverpayIssueBillingKeyBypass {
  /// 하부 가맹점 명
  final String? subMerchantName;

  /// 하부 가맹점 ID
  final String? subMerchantId;

  NaverpayIssueBillingKeyBypass({this.subMerchantName, this.subMerchantId});

  Map<String, dynamic> toJson() => {
    if (subMerchantName != null) 'subMerchantName': subMerchantName!,
    if (subMerchantId != null) 'subMerchantId': subMerchantId!,
  };
}
