// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 결제 비밀번호 등록 Skip 여부
enum SmartroV2IsPwdPass {
  /// 비밀번호 설정 미사용
  Y('Y'),

  /// 비밀번호 설정 사용
  N('N');

  final String _value;
  const SmartroV2IsPwdPass(String value) : _value = value;
  String toJson() => _value;
  static SmartroV2IsPwdPass fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
