// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// UI 스타일(기본: RED)
enum SmartroV2SkinColor {
  RED('RED'),
  GREEN('GREEN'),
  BLUE('BLUE'),
  PURPLE('PURPLE');

  final String _value;
  const SmartroV2SkinColor(String value) : _value = value;
  String toJson() => _value;
}
