// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/smartro_v_2_is_pwd_pass.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/smartro_v_2_skin_color.dart';

/// **스마트로 bypass 파라미터**
class SmartroV2IssueBillingKeyBypass {
  /// UI 스타일(기본: RED)
  final SmartroV2SkinColor? skinColor;

  /// 결제 비밀번호 등록 Skip 여부
  final SmartroV2IsPwdPass? isPwdPass;

  SmartroV2IssueBillingKeyBypass({this.skinColor, this.isPwdPass});

  Map<String, dynamic> toJson() => {
    if (skinColor != null) 'SkinColor': skinColor!.toJson(),
    if (isPwdPass != null) 'IsPwdPass': isPwdPass!.toJson(),
  };
}
