// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **토스페이 bypass 파라미터**
class TosspayV2IssueBillingKeyBypass {
  /// 암호화된 사용자 CI
  final String? encryptedUserCi;

  TosspayV2IssueBillingKeyBypass({this.encryptedUserCi});

  Map<String, dynamic> toJson() => {
    if (encryptedUserCi != null) 'encryptedUserCi': encryptedUserCi!,
  };

  static TosspayV2IssueBillingKeyBypass fromJson(Map<String, dynamic> json) =>
      TosspayV2IssueBillingKeyBypass(
        encryptedUserCi: json['encryptedUserCi'] as String?,
      );
}
