// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **웰컴페이먼츠 bypass 파라미터**
class WelcomeIssueBillingKeyBypass {
  /// 메인 로고 URL (크기: 89x19)
  final String? logoUrl;

  /// 서브 로고 URL (크기: 64x13)
  final String? logo2Nd;

  WelcomeIssueBillingKeyBypass({this.logoUrl, this.logo2Nd});

  Map<String, dynamic> toJson() => {
    if (logoUrl != null) 'logo_url': logoUrl!,
    if (logo2Nd != null) 'logo_2nd': logo2Nd!,
  };
}
