// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 배송지 정보
class EximbayV2ShipTo {
  /// 배송지 도시
  final String? city;

  /// 배송지 국가 (ISO 3166 두 자리 국가 코드)
  final String? country;

  /// 수신인의 성을 제외한 이름
  final String? firstName;

  /// 수신인의 성
  final String? lastName;

  /// 수신인 전화번호
  final String? phoneNumber;

  /// 배송지 우편번호
  final String? postalCode;

  /// 배송지가 미국 혹은 캐나다인 경우, 배송지 주 정보
  final String? state;

  /// 배송지 상세 주소
  final String? street1;

  EximbayV2ShipTo({
    this.city,
    this.country,
    this.firstName,
    this.lastName,
    this.phoneNumber,
    this.postalCode,
    this.state,
    this.street1,
  });

  Map<String, dynamic> toJson() => {
    if (city != null) 'city': city!,
    if (country != null) 'country': country!,
    if (firstName != null) 'first_name': firstName!,
    if (lastName != null) 'last_name': lastName!,
    if (phoneNumber != null) 'phone_number': phoneNumber!,
    if (postalCode != null) 'postal_code': postalCode!,
    if (state != null) 'state': state!,
    if (street1 != null) 'street1': street1!,
  };

  static EximbayV2ShipTo fromJson(Map<String, dynamic> json) => EximbayV2ShipTo(
    city: json['city'] as String?,
    country: json['country'] as String?,
    firstName: json['first_name'] as String?,
    lastName: json['last_name'] as String?,
    phoneNumber: json['phone_number'] as String?,
    postalCode: json['postal_code'] as String?,
    state: json['state'] as String?,
    street1: json['street1'] as String?,
  );
}
