// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 상점 정보
class EximbayV2Merchant {
  /// 상점명
  final String? shop;

  /// 파트너 코드
  final String? partnerCode;

  EximbayV2Merchant({this.shop, this.partnerCode});

  Map<String, dynamic> toJson() => {
    if (shop != null) 'shop': shop!,
    if (partnerCode != null) 'partner_code': partnerCode!,
  };

  static EximbayV2Merchant fromJson(Map<String, dynamic> json) =>
      EximbayV2Merchant(
        shop: json['shop'] as String?,
        partnerCode: json['partner_code'] as String?,
      );
}
