// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_settings_call_from_app.dart';

/// 설정 정보
class EximbayV2Settings {
  /// 인앱 웹뷰 여부
  final EximbayV2SettingsCallFromApp? callFromApp;

  /// 해외 결제 가맹점에서 국내 결제를 사용할 경우 `KR`
  final String? issuerCountry;

  /// 입금 만료 일자 (yyyyMMddHH)
  final String? virtualaccountExpiryDate;

  EximbayV2Settings({
    this.callFromApp,
    this.issuerCountry,
    this.virtualaccountExpiryDate,
  });

  Map<String, dynamic> toJson() => {
    if (callFromApp != null) 'call_from_app': callFromApp!.toJson(),
    if (issuerCountry != null) 'issuer_country': issuerCountry!,
    if (virtualaccountExpiryDate != null)
      'virtualaccount_expiry_date': virtualaccountExpiryDate!,
  };

  static EximbayV2Settings fromJson(Map<String, dynamic> json) =>
      EximbayV2Settings(
        callFromApp:
            json['call_from_app'] != null
                ? EximbayV2SettingsCallFromApp.fromJson(json['call_from_app'])
                : null,
        issuerCountry: json['issuer_country'] as String?,
        virtualaccountExpiryDate: json['virtualaccount_expiry_date'] as String?,
      );
}
