// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 청구지 정보
class EximbayV2BillTo {
  /// 청구지 도시
  final String? city;

  /// 청구지 국가 (ISO 3166 두 자리 국가 코드)
  final String? country;

  /// 청구 카드 명의자의 성을 제외한 이름
  final String? firstName;

  /// 청구 카드 명의자의 성
  final String? lastName;

  /// 청구 카드 명의자의 전화번호
  final String? phoneNumber;

  /// 청구지 우편번호
  final String? postalCode;

  /// 청구지가 미국 혹은 캐나다인 경우, 청구지 주 정보
  final String? state;

  /// 청구지 상세 주소
  final String? street1;

  EximbayV2BillTo({
    this.city,
    this.country,
    this.firstName,
    this.lastName,
    this.phoneNumber,
    this.postalCode,
    this.state,
    this.street1,
  });

  Map<String, dynamic> toJson() => {
    if (city != null) 'city': city!,
    if (country != null) 'country': country!,
    if (firstName != null) 'first_name': firstName!,
    if (lastName != null) 'last_name': lastName!,
    if (phoneNumber != null) 'phone_number': phoneNumber!,
    if (postalCode != null) 'postal_code': postalCode!,
    if (state != null) 'state': state!,
    if (street1 != null) 'street1': street1!,
  };
}
