// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_paypal_ispp.dart';

/// 페이팔 정보
class EximbayV2Paypal {
  /// PayPal ISPP 정보
  ///
  /// ISPP 서비스를 신청하여 엑심베이 및 PayPal의 심사를 통과한 경우 사용합니다.
  /// 기본적으로 모든 값이 필수이며, 전송 불가능할 경우 엑심베이에 사전 문의해야 합니다.
  final EximbayV2PaypalIspp? ispp;

  EximbayV2Paypal({this.ispp});

  Map<String, dynamic> toJson() => {if (ispp != null) 'ispp': ispp!.toJson()};
}
