// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 인앱 웹뷰 여부
enum EximbayV2SettingsCallFromApp {
  Y('Y'),
  N('N');

  final String _value;
  const EximbayV2SettingsCallFromApp(String value) : _value = value;
  String toJson() => _value;
}
