// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class EximbayV2Surcharge {
  /// 항목명
  final String? name;

  /// 수량
  final String? quantity;

  /// 단가 (음수 가능)
  final String? unitPrice;

  EximbayV2Surcharge({this.name, this.quantity, this.unitPrice});

  Map<String, dynamic> toJson() => {
    if (name != null) 'name': name!,
    if (quantity != null) 'quantity': quantity!,
    if (unitPrice != null) 'unit_price': unitPrice!,
  };
}
