// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_tax_receipt_status.dart';

/// 세금 정보
class EximbayV2Tax {
  /// 현금영수증 발급 여부
  final EximbayV2TaxReceiptStatus? receiptStatus;

  EximbayV2Tax({this.receiptStatus});

  Map<String, dynamic> toJson() => {
    if (receiptStatus != null) 'receipt_status': receiptStatus!.toJson(),
  };

  static EximbayV2Tax fromJson(Map<String, dynamic> json) => EximbayV2Tax(
    receiptStatus:
        json['receipt_status'] != null
            ? EximbayV2TaxReceiptStatus.fromJson(json['receipt_status'])
            : null,
  );
}
