// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_bill_to.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_merchant.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_payment.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_settings.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_ship_to.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_surcharge.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2_tax.dart';

/// 엑심베이 V2 bypass 파라미터
class EximbayV2Bypass {
  /// 결제 정보
  final EximbayV2Payment? payment;

  /// 상점 정보
  final EximbayV2Merchant? merchant;

  /// 세금 정보
  final EximbayV2Tax? tax;

  /// 최대 3개의 추가 비용 목록
  final List<EximbayV2Surcharge>? surcharge;

  /// 배송지 정보
  final EximbayV2ShipTo? shipTo;

  /// 청구지 정보
  final EximbayV2BillTo? billTo;

  /// 설정 정보
  final EximbayV2Settings? settings;

  EximbayV2Bypass({
    this.payment,
    this.merchant,
    this.tax,
    this.surcharge,
    this.shipTo,
    this.billTo,
    this.settings,
  });

  Map<String, dynamic> toJson() => {
    if (payment != null) 'payment': payment!.toJson(),
    if (merchant != null) 'merchant': merchant!.toJson(),
    if (tax != null) 'tax': tax!.toJson(),
    if (surcharge != null)
      'surcharge': surcharge!.map((e) => e.toJson()).toList(),
    if (shipTo != null) 'ship_to': shipTo!.toJson(),
    if (billTo != null) 'bill_to': billTo!.toJson(),
    if (settings != null) 'settings': settings!.toJson(),
  };

  static EximbayV2Bypass fromJson(Map<String, dynamic> json) => EximbayV2Bypass(
    payment:
        json['payment'] != null
            ? EximbayV2Payment.fromJson(json['payment'])
            : null,
    merchant:
        json['merchant'] != null
            ? EximbayV2Merchant.fromJson(json['merchant'])
            : null,
    tax: json['tax'] != null ? EximbayV2Tax.fromJson(json['tax']) : null,
    surcharge:
        (json['surcharge'] as List?)
            ?.map((e) => EximbayV2Surcharge.fromJson(e))
            .toList(),
    shipTo:
        json['ship_to'] != null
            ? EximbayV2ShipTo.fromJson(json['ship_to'])
            : null,
    billTo:
        json['bill_to'] != null
            ? EximbayV2BillTo.fromJson(json['bill_to'])
            : null,
    settings:
        json['settings'] != null
            ? EximbayV2Settings.fromJson(json['settings'])
            : null,
  );
}
