// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 현금영수증 발급 여부
enum EximbayV2TaxReceiptStatus {
  Y('Y'),
  N('N');

  final String _value;
  const EximbayV2TaxReceiptStatus(String value) : _value = value;
  String toJson() => _value;
}
