// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// PayPal ISPP 정보
///
/// ISPP 서비스를 신청하여 엑심베이 및 PayPal의 심사를 통과한 경우 사용합니다.
/// 기본적으로 모든 값이 필수이며, 전송 불가능할 경우 엑심베이에 사전 문의해야 합니다.
class EximbayV2PaypalIspp {
  /// 고객사의 구매자 고유 ID
  final String? senderAccountId;

  /// 구매자 이름
  final String? senderFirstName;

  /// 구매자 성
  final String? senderLastName;

  /// 구매자 이메일
  final String? senderEmail;

  /// 구매자 전화번호
  ///
  /// [E.123 international format](https://www.itu.int/rec/t-rec-e.123/en) 형식입니다.
  final String? senderPhone;

  /// 구매자 국가 코드
  ///
  /// [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
  final String? senderCountryCode;

  /// 구매자 계정 생성 일자
  ///
  /// `YYYY-MM-DD HH:mm:ss` 형식으로 입력합니다.
  final String? senderCreateDate;

  EximbayV2PaypalIspp({
    this.senderAccountId,
    this.senderFirstName,
    this.senderLastName,
    this.senderEmail,
    this.senderPhone,
    this.senderCountryCode,
    this.senderCreateDate,
  });

  Map<String, dynamic> toJson() => {
    if (senderAccountId != null) 'sender_account_id': senderAccountId!,
    if (senderFirstName != null) 'sender_first_name': senderFirstName!,
    if (senderLastName != null) 'sender_last_name': senderLastName!,
    if (senderEmail != null) 'sender_email': senderEmail!,
    if (senderPhone != null) 'sender_phone': senderPhone!,
    if (senderCountryCode != null) 'sender_country_code': senderCountryCode!,
    if (senderCreateDate != null) 'sender_create_date': senderCreateDate!,
  };
}
