// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 갤럭시아 bypass 파라미터
class GalaxiaPaymentBypass {
  /// 구매 상품 코드
  final String? itemCode;

  GalaxiaPaymentBypass({this.itemCode});

  Map<String, dynamic> toJson() => {
    if (itemCode != null) 'ITEM_CODE': itemCode!,
  };

  static GalaxiaPaymentBypass fromJson(Map<String, dynamic> json) =>
      GalaxiaPaymentBypass(itemCode: json['ITEM_CODE'] as String?);
}
