// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 하이픈 bypass 파라미터
class HyphenBypass {
  final String? designCd;

  HyphenBypass({this.designCd});

  Map<String, dynamic> toJson() => {
    if (designCd != null) 'designCd': designCd!,
  };

  static HyphenBypass fromJson(Map<String, dynamic> json) =>
      HyphenBypass(designCd: json['designCd'] as String?);
}
