// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 결제창 UI 설정
class InicisJpPaymentUI {
  /// **결제창 색상**
  ///
  /// 가능한 값:
  ///
  /// - `red1`
  /// - `red2`
  /// - `red3`
  /// - `red4`
  /// - `orange`
  /// - `yellow`
  /// - `black`
  /// - `purple`
  /// - `green`
  /// - `blue1`
  /// - `blue2`
  /// - `blue3`
  /// - `blue4`
  /// - `blue5`
  /// - `blue6`
  final String? colorTheme;

  /// **가맹점 로고 이미지 URL**
  ///
  /// 69 \* 20 픽셀 크기의 이미지 URL
  final String? logoUrl;

  InicisJpPaymentUI({this.colorTheme, this.logoUrl});

  Map<String, dynamic> toJson() => {
    if (colorTheme != null) 'colorTheme': colorTheme!,
    if (logoUrl != null) 'logoUrl': logoUrl!,
  };
}
