// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/inicis_jp_payment_ui.dart';

/// 이니시스 일본 bypass 파라미터
class InicisJpBypass {
  /// 결제창 UI 설정
  final InicisJpPaymentUI? paymentUi;

  InicisJpBypass({this.paymentUi});

  Map<String, dynamic> toJson() => {
    if (paymentUi != null) 'paymentUI': paymentUi!.toJson(),
  };
}
