// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 카카오페이 bypass 파라미터
class KakaopayPaymentBypass {
  /// 카카오페이 결제창에 띄워줄 사용자 정의 문구
  final String? customMessage;

  KakaopayPaymentBypass({this.customMessage});

  Map<String, dynamic> toJson() => {
    if (customMessage != null) 'custom_message': customMessage!,
  };
}
