// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 포인트 결제의 경우 신용카드 + 포인트 결제인데, N으로 설정 시 포인트로만 결제가 이루어짐
enum KcpV2ComplexPnt {
  Y('Y'),
  N('N');

  final String _value;
  const KcpV2ComplexPnt(String value) : _value = value;
  String toJson() => _value;
}
