// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/kcp_v_2_complex_pnt.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/kcp_v_2_disp_tax.dart';

/// NHN KCP bypass 파라미터
class KcpV2Bypass {
  final String? skinIndx;
  final String? siteLogo;
  final String shopUserId;
  final String? kcpPayTitle;

  /// 포인트 결제의 경우 신용카드 + 포인트 결제인데, N으로 설정 시 포인트로만 결제가 이루어짐
  final KcpV2ComplexPnt? complexPntYn;
  final String? ptMemcorpCd;

  /// 가상계좌, 계좌이체 시 현금영수증 노출 여부
  final KcpV2DispTax? dispTaxYn;

  /// 결제창에 노출될 고객사 상호명
  final String? siteName;

  /// 에스크로 배송 예상 소요일
  final String? deliTerm;

  KcpV2Bypass({
    this.skinIndx,
    this.siteLogo,
    required this.shopUserId,
    this.kcpPayTitle,
    this.complexPntYn,
    this.ptMemcorpCd,
    this.dispTaxYn,
    this.siteName,
    this.deliTerm,
  });

  Map<String, dynamic> toJson() => {
    if (skinIndx != null) 'skin_indx': skinIndx!,
    if (siteLogo != null) 'site_logo': siteLogo!,
    'shop_user_id': shopUserId,
    if (kcpPayTitle != null) 'kcp_pay_title': kcpPayTitle!,
    if (complexPntYn != null) 'complex_pnt_yn': complexPntYn!.toJson(),
    if (ptMemcorpCd != null) 'pt_memcorp_cd': ptMemcorpCd!,
    if (dispTaxYn != null) 'disp_tax_yn': dispTaxYn!.toJson(),
    if (siteName != null) 'site_name': siteName!,
    if (deliTerm != null) 'deli_term': deliTerm!,
  };

  static KcpV2Bypass fromJson(Map<String, dynamic> json) => KcpV2Bypass(
    skinIndx: json['skin_indx'] as String?,
    siteLogo: json['site_logo'] as String?,
    shopUserId: json['shop_user_id'] as String,
    kcpPayTitle: json['kcp_pay_title'] as String?,
    complexPntYn:
        json['complex_pnt_yn'] != null
            ? KcpV2ComplexPnt.fromJson(json['complex_pnt_yn'])
            : null,
    ptMemcorpCd: json['pt_memcorp_cd'] as String?,
    dispTaxYn:
        json['disp_tax_yn'] != null
            ? KcpV2DispTax.fromJson(json['disp_tax_yn'])
            : null,
    siteName: json['site_name'] as String?,
    deliTerm: json['deli_term'] as String?,
  );
}
