// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 가상계좌, 계좌이체 시 현금영수증 노출 여부
enum KcpV2DispTax {
  Y('Y'),
  N('N'),
  R('R'),
  E('E');

  final String _value;
  const KcpV2DispTax(String value) : _value = value;
  String toJson() => _value;
  static KcpV2DispTax fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
