// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/kpn_card_select.dart';

/// KPN bypass 파라미터
class KpnBypass {
  /// - 해외카드 (VISA + MASTER + JCB) : `GLOBAL`
  /// - 11Pay (SKPay) : `11PAY`
  /// - 구인증 : `LEGACY_AUTH`
  /// - 키인 : `KEY_IN`
  final List<KpnCardSelect>? cardSelect;

  KpnBypass({this.cardSelect});

  Map<String, dynamic> toJson() => {
    if (cardSelect != null)
      'CardSelect': cardSelect!.map((e) => e.toJson()).toList(),
  };

  static KpnBypass fromJson(Map<String, dynamic> json) => KpnBypass(
    cardSelect:
        (json['CardSelect'] as List?)
            ?.map((e) => KpnCardSelect.fromJson(e))
            .toList(),
  );
}
