// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

enum KpnCardSelect {
  /// 해외카드
  GLOBAL('GLOBAL'),

  /// 11Pay
  _11PAY('11PAY'),

  /// 구인증
  LEGACY_AUTH('LEGACY_AUTH'),

  /// 키인
  KEY_IN('KEY_IN');

  final String _value;
  const KpnCardSelect(String value) : _value = value;
  String toJson() => _value;
  static KpnCardSelect fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
