// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/ksnet_snd_qpay_type.dart';

/// KSNET bypass 파라미터
class KsnetPaymentBypass {
  /// 간편 결제 표시 구분
  final KsnetSndQpayType? sndQpayType;

  /// **KSNET 간편결제 다이렉트 여부**
  final bool? easyPayDirect;

  KsnetPaymentBypass({this.sndQpayType, this.easyPayDirect});

  Map<String, dynamic> toJson() => {
    if (sndQpayType != null) 'sndQpayType': sndQpayType!.toJson(),
    if (easyPayDirect != null) 'easyPayDirect': easyPayDirect!,
  };
}
