// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 간편 결제 표시 구분
enum KsnetSndQpayType {
  /// 간편 결제 표시
  _1('1'),

  /// 간편 결제 미표시
  _0('0');

  final String _value;
  const KsnetSndQpayType(String value) : _value = value;
  String toJson() => _value;
}
