// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 카드 결제창에서 카카오페이 결제시 허용할 결제수단
enum KsnetSndKakaopayType {
  /// 카드 결제만 허용
  CARD('CARD'),

  /// 카카오머니 결제만 허용
  MONEY('MONEY');

  final String _value;
  const KsnetSndKakaopayType(String value) : _value = value;
  String toJson() => _value;
}
