// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 결제 수단 별 bypass할 값
class MobiliansV2PayOptions {
  /// 우리카드 우리페이(WON카드, WON뱅킹) 결제만 제공할지 여부
  ///
  /// - `Y`: 사용
  /// - `N`: 미사용
  final String? cnPayAppUseYn;

  /// 우리카드 우리페이 결제수단 목록 WON카드, WON뱅킹에서 단독으로 결제할지 여부
  /// (cn\_pay\_app\_use\_yn이 "Y"이어야 사용가능)
  ///
  /// - `01`: WON카드
  /// - `02`: WON뱅킹
  final String? cnPayAppUseCd;

  /// 간편결제 다이렉트 호출 시 사용할 결제수단
  ///
  /// - `C`: 카드
  /// - `P`: 네이버페이 포인트 (네이버페이에서만 사용 가능)
  /// - `M`: 카카오페이 머니, 토스머니 (카카오페이, 토스페이에서만 사용 가능)
  final String? epPayType;

  /// 휴대폰 결제창에서 휴대폰 번호를 고정할지 여부
  ///
  /// - `Y`: 고정 사용
  /// - `N`: 미사용
  final String? mcFixNo;

  /// 휴대폰 결제에서 ARS 인증 사용 여부
  ///
  /// - `SAFECALL`: 고정 사용
  final String? mcSafeCall;

  /// 휴대폰 결제에서 간소화 결제 미사용 여부
  ///
  /// - `Y`: 간소화 결제 미사용
  final String? mcSimplePay;

  /// 계좌이체 결제에서 에스크로 구매 비밀먼호
  /// (에스크로 적용하여 뱅크페이 다이렉트 호출 시 필수 입력)
  final String? raEscrowPassword;

  /// 계좌이체 결제에서 뱅크페이 다이렉트 호출 여부
  ///
  /// - `Y`: 사용
  /// - `N`: 미사용
  final String? raDirect;

  /// 가상계좌 결제창에서 현금영수증 발급 항목 노출 여부
  ///
  /// - `Y`: 노출
  /// - `N`: 미노출
  final String? vaCashReceipt;

  /// 가상계좌 결제창에서 에스크로 사용 설정 항목 노출 여부
  ///
  /// - `Y`: 노출
  /// - `N`: 미노출
  final String? vaEscrow;

  /// 가상계좌 결제창에서 이메일 입력 필수 여부
  ///
  /// - `Y`: 필수 입력
  /// - `N`: 선택 입력
  final String? vaEmail;

  MobiliansV2PayOptions({
    this.cnPayAppUseYn,
    this.cnPayAppUseCd,
    this.epPayType,
    this.mcFixNo,
    this.mcSafeCall,
    this.mcSimplePay,
    this.raEscrowPassword,
    this.raDirect,
    this.vaCashReceipt,
    this.vaEscrow,
    this.vaEmail,
  });

  Map<String, dynamic> toJson() => {
    if (cnPayAppUseYn != null) 'cn_pay_app_use_yn': cnPayAppUseYn!,
    if (cnPayAppUseCd != null) 'cn_pay_app_use_cd': cnPayAppUseCd!,
    if (epPayType != null) 'ep_pay_type': epPayType!,
    if (mcFixNo != null) 'mc_fix_no': mcFixNo!,
    if (mcSafeCall != null) 'mc_safe_call': mcSafeCall!,
    if (mcSimplePay != null) 'mc_simple_pay': mcSimplePay!,
    if (raEscrowPassword != null) 'ra_escrow_password': raEscrowPassword!,
    if (raDirect != null) 'ra_direct': raDirect!,
    if (vaCashReceipt != null) 'va_cash_receipt': vaCashReceipt!,
    if (vaEscrow != null) 'va_escrow': vaEscrow!,
    if (vaEmail != null) 'va_email': vaEmail!,
  };

  static MobiliansV2PayOptions fromJson(Map<String, dynamic> json) =>
      MobiliansV2PayOptions(
        cnPayAppUseYn: json['cn_pay_app_use_yn'] as String?,
        cnPayAppUseCd: json['cn_pay_app_use_cd'] as String?,
        epPayType: json['ep_pay_type'] as String?,
        mcFixNo: json['mc_fix_no'] as String?,
        mcSafeCall: json['mc_safe_call'] as String?,
        mcSimplePay: json['mc_simple_pay'] as String?,
        raEscrowPassword: json['ra_escrow_password'] as String?,
        raDirect: json['ra_direct'] as String?,
        vaCashReceipt: json['va_cash_receipt'] as String?,
        vaEscrow: json['va_escrow'] as String?,
        vaEmail: json['va_email'] as String?,
      );
}
