// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 추가 설정 옵션
class MobiliansV2HiddenOptions {
  /// 결제창 하단안내문구영역 숨김 여부
  ///
  /// - `Y`: 숨김
  /// - `N`: 노출 (default)
  final String? infoArea;

  /// 결제창 footer영역 숨김 여부
  ///
  /// - `Y`: 숨김
  /// - `N`: 노출 (default)
  final String? footerArea;

  /// 결제창 상품정보영역 숨김 여부
  ///
  /// - `Y`: 숨김
  /// - `N`: 노출 (default)
  final String? productArea;

  /// 결제창 이메일입력영역 숨김 여부
  ///
  /// - `Y`: 숨김
  /// - `N`: 노출 (default)
  final String? emailArea;

  MobiliansV2HiddenOptions({
    this.infoArea,
    this.footerArea,
    this.productArea,
    this.emailArea,
  });

  Map<String, dynamic> toJson() => {
    if (infoArea != null) 'info_area': infoArea!,
    if (footerArea != null) 'footer_area': footerArea!,
    if (productArea != null) 'product_area': productArea!,
    if (emailArea != null) 'email_area': emailArea!,
  };
}
