// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/mobilians_v_2_hidden_options.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/mobilians_v_2_pay_options.dart';

/// 모빌리언스 V2 bypass 파라미터
class MobiliansV2Bypass {
  /// 담당자 이메일 (결제 결과 노티 실패 또는 입금 완료 시 알림이 발송될 이메일)
  final String? notiEmail;

  /// 고객사 로고 표기 여부
  ///
  /// - `Y`: 표기 (사전 협의 된 이미지 등록 필요)
  /// - `N`: 미표기
  final String? cpLogo;

  /// 법인 단위 로고 표기 여부
  ///
  /// - `Y`: 표기 (사전 협의 된 이미지 등록 필요)
  /// - `N`: 미표기
  final String? entpLogo;

  /// 결제창 색상 설정 (HTML 색상코드)
  /// ex) #006EB9
  final String? cssType;

  /// 고객사 UI 설정
  final String? cpUi;

  /// 결제 수단 별 bypass할 값
  final MobiliansV2PayOptions? payOptions;

  /// 추가 설정 옵션
  final MobiliansV2HiddenOptions? hiddenOptions;

  /// 상품권 결제창 고객사 로고 표시 여부
  ///
  /// - `Y`: 표시 (사전 협의 된 이미지 등록 필요)
  /// - `N`: 미표시, 모빌리언스 로고 표시 (default)
  final String? logoYn;

  /// 상품권 결제창 안내문영역 노출 여부
  ///
  /// - `Y`: 표시 (default)
  /// - `N`: 미표시
  final String? infoareaYn;

  /// 상품권 결제창 하단 안내영역 노출 여부
  ///
  /// - `Y`: 표시 (default)
  /// - `N`: 미표시
  final String? footerYn;

  /// 상품권 결제창 이용약관영역 노출 여부
  ///
  /// - `Y`: 노출 (default)
  /// - `N`: 숨김
  final String? contractHidden;

  /// 상품권 결제창 이메일입력영역 숨김 여부
  ///
  /// - `Y`: 숨김
  /// - `N`: 노출 (default)
  final String? emailHidden;

  MobiliansV2Bypass({
    this.notiEmail,
    this.cpLogo,
    this.entpLogo,
    this.cssType,
    this.cpUi,
    this.payOptions,
    this.hiddenOptions,
    this.logoYn,
    this.infoareaYn,
    this.footerYn,
    this.contractHidden,
    this.emailHidden,
  });

  Map<String, dynamic> toJson() => {
    if (notiEmail != null) 'noti_email': notiEmail!,
    if (cpLogo != null) 'cp_logo': cpLogo!,
    if (entpLogo != null) 'entp_logo': entpLogo!,
    if (cssType != null) 'css_type': cssType!,
    if (cpUi != null) 'cp_ui': cpUi!,
    if (payOptions != null) 'pay_options': payOptions!.toJson(),
    if (hiddenOptions != null) 'hidden_options': hiddenOptions!.toJson(),
    if (logoYn != null) 'LOGO_YN': logoYn!,
    if (infoareaYn != null) 'INFOAREA_YN': infoareaYn!,
    if (footerYn != null) 'FOOTER_YN': footerYn!,
    if (contractHidden != null) 'CONTRACT_HIDDEN': contractHidden!,
    if (emailHidden != null) 'EMAIL_HIDDEN': emailHidden!,
  };

  static MobiliansV2Bypass fromJson(Map<String, dynamic> json) =>
      MobiliansV2Bypass(
        notiEmail: json['noti_email'] as String?,
        cpLogo: json['cp_logo'] as String?,
        entpLogo: json['entp_logo'] as String?,
        cssType: json['css_type'] as String?,
        cpUi: json['cp_ui'] as String?,
        payOptions:
            json['pay_options'] != null
                ? MobiliansV2PayOptions.fromJson(json['pay_options'])
                : null,
        hiddenOptions:
            json['hidden_options'] != null
                ? MobiliansV2HiddenOptions.fromJson(json['hidden_options'])
                : null,
        logoYn: json['LOGO_YN'] as String?,
        infoareaYn: json['INFOAREA_YN'] as String?,
        footerYn: json['FOOTER_YN'] as String?,
        contractHidden: json['CONTRACT_HIDDEN'] as String?,
        emailHidden: json['EMAIL_HIDDEN'] as String?,
      );
}
