// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/naverpay_product_item.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/naverpay_sub_merchant_info.dart';

/// 네이버페이 bypass 파라미터
class NaverpayPaymentBypass {
  /// 이용 완료일(YYYYMMDD)
  final String? useCfmYmdt;
  final List<NaverpayProductItem> productItems;

  /// 하부 가맹점 정보. PG 업종 가맹점인 경우에만 필수 값
  final NaverpaySubMerchantInfo? subMerchantInfo;

  /// 배송비
  final int? deliveryFee;

  NaverpayPaymentBypass({
    this.useCfmYmdt,
    required this.productItems,
    this.subMerchantInfo,
    this.deliveryFee,
  });

  Map<String, dynamic> toJson() => {
    if (useCfmYmdt != null) 'useCfmYmdt': useCfmYmdt!,
    'productItems': productItems.map((e) => e.toJson()).toList(),
    if (subMerchantInfo != null) 'subMerchantInfo': subMerchantInfo!.toJson(),
    if (deliveryFee != null) 'deliveryFee': deliveryFee!,
  };

  static NaverpayPaymentBypass fromJson(Map<String, dynamic> json) =>
      NaverpayPaymentBypass(
        useCfmYmdt: json['useCfmYmdt'] as String?,
        productItems:
            (json['productItems'] as List)
                .map((e) => NaverpayProductItem.fromJson(e))
                .toList(),
        subMerchantInfo:
            json['subMerchantInfo'] != null
                ? NaverpaySubMerchantInfo.fromJson(json['subMerchantInfo'])
                : null,
        deliveryFee: json['deliveryFee'] as int?,
      );
}
