// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 하부 가맹점 정보. PG 업종 가맹점인 경우에만 필수 값
class NaverpaySubMerchantInfo {
  /// 하부 가맹점 명
  final String subMerchantName;

  /// 하부 가맹점 ID
  final String subMerchantId;

  /// 하부 가맹점 사업자 번호(숫자 10자리)
  final String subMerchantBusinessNo;

  /// 하부 가맹점 결제 키
  final String subMerchantPayId;

  /// 하부 가맹점 대표 전화번호
  final String subMerchantTelephoneNo;

  /// 하부 가맹점 고객 서비스 URL
  final String subMerchantCustomerServiceUrl;

  NaverpaySubMerchantInfo({
    required this.subMerchantName,
    required this.subMerchantId,
    required this.subMerchantBusinessNo,
    required this.subMerchantPayId,
    required this.subMerchantTelephoneNo,
    required this.subMerchantCustomerServiceUrl,
  });

  Map<String, dynamic> toJson() => {
    'subMerchantName': subMerchantName,
    'subMerchantId': subMerchantId,
    'subMerchantBusinessNo': subMerchantBusinessNo,
    'subMerchantPayId': subMerchantPayId,
    'subMerchantTelephoneNo': subMerchantTelephoneNo,
    'subMerchantCustomerServiceUrl': subMerchantCustomerServiceUrl,
  };
}
