// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 결제 상품 유입경로
enum NaverpayProductItemPayReferrer {
  NAVER_BOOK('NAVER_BOOK'),
  NAVER_MUSIC('NAVER_MUSIC'),
  NAVER_SHOPPING('NAVER_SHOPPING'),
  NAVER_MAP('NAVER_MAP'),
  NAVER_PLACE('NAVER_PLACE'),
  SEARCH_AD('SEARCH_AD'),
  NAVER_SEARCH('NAVER_SEARCH'),
  BRAND_SEARCH('BRAND_SEARCH'),
  PARTNER_DIRECT('PARTNER_DIRECT'),
  ETC('ETC');

  final String _value;
  const NaverpayProductItemPayReferrer(String value) : _value = value;
  String toJson() => _value;
}
