// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/naverpay_product_item_pay_referrer.dart';

class NaverpayProductItem {
  /// 결제 상품 유형
  final String categoryType;

  /// 결제 상품 분류
  final String categoryId;

  /// 결제 상품 식별값
  final String uid;

  /// 상품명
  final String name;

  /// 결제 상품 유입경로
  final NaverpayProductItemPayReferrer? payReferrer;

  /// 시작일(YYYYMMDD)
  final String? startDate;

  /// 종료일(YYYYMMDD)
  final String? endDate;

  /// 하위 판매자 식별키
  final String? sellerId;

  /// 결제 상품 개수
  final int count;

  NaverpayProductItem({
    required this.categoryType,
    required this.categoryId,
    required this.uid,
    required this.name,
    this.payReferrer,
    this.startDate,
    this.endDate,
    this.sellerId,
    required this.count,
  });

  Map<String, dynamic> toJson() => {
    'categoryType': categoryType,
    'categoryId': categoryId,
    'uid': uid,
    'name': name,
    if (payReferrer != null) 'payReferrer': payReferrer!.toJson(),
    if (startDate != null) 'startDate': startDate!,
    if (endDate != null) 'endDate': endDate!,
    if (sellerId != null) 'sellerId': sellerId!,
    'count': count,
  };
}
