// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 삼성페이 고객사 유형 (01: 삼성페이 內 쇼핑 / 99: 기타 (기본값))
enum NiceV2SamPayMallType {
  /// 삼성페이 內 쇼핑
  _01('01'),

  /// 기타 (기본값)
  _99('99');

  final String _value;
  const NiceV2SamPayMallType(String value) : _value = value;
  String toJson() => _value;
  static NiceV2SamPayMallType fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
