// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 결제창 스크롤 미사용 여부 (PC Only, Y: 미사용 / N(default): 사용)
enum NiceV2DisableScroll {
  Y('Y'),
  N('N');

  final String _value;
  const NiceV2DisableScroll(String value) : _value = value;
  String toJson() => _value;
}
