// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 결제창 스킨 색상 설정
///
/// `"red", "green", "purple", "gray", "dark"` 중 하나의 값으로 입력해주세요.
enum NiceV2SkinType {
  red('red'),
  green('green'),
  purple('purple'),
  gray('gray'),
  dark('dark');

  final String _value;
  const NiceV2SkinType(String value) : _value = value;
  String toJson() => _value;
  static NiceV2SkinType fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
