// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 다이렉트 호출 결제 수단 (BANK: 계좌이체/CELLPHONE: 휴대폰 소액결제)
enum NiceV2DirectShow {
  /// 계좌이체
  BANK('BANK'),

  /// 휴대폰 소액결제
  CELLPHONE('CELLPHONE');

  final String _value;
  const NiceV2DirectShow(String value) : _value = value;
  String toJson() => _value;
}
