// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// Paymentwall bypass 파라미터
class PaymentwallBypass {
  /// **위젯 코드**
  final String? widget;

  /// **결제수단 코드**
  final String? ps;

  /// **국가 코드 (ISO 3166 두 자리)**
  final String? countryCode;

  PaymentwallBypass({this.widget, this.ps, this.countryCode});

  Map<String, dynamic> toJson() => {
    if (widget != null) 'widget': widget!,
    if (ps != null) 'ps': ps!,
    if (countryCode != null) 'country_code': countryCode!,
  };
}
