// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/paypal_v_2_payment_source_paypal_experience_context_landing_page.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/paypal_v_2_payment_source_paypal_experience_context_payment_method_preference.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/paypal_v_2_payment_source_paypal_experience_context_shipping_preference.dart';

class PaypalV2PaymentSourcePaypalExperienceContext {
  final String? brandName;
  final PaypalV2PaymentSourcePaypalExperienceContextShippingPreference?
  shippingPreference;
  final PaypalV2PaymentSourcePaypalExperienceContextLandingPage? landingPage;
  final PaypalV2PaymentSourcePaypalExperienceContextPaymentMethodPreference?
  paymentMethodPreference;

  PaypalV2PaymentSourcePaypalExperienceContext({
    this.brandName,
    this.shippingPreference,
    this.landingPage,
    this.paymentMethodPreference,
  });

  Map<String, dynamic> toJson() => {
    if (brandName != null) 'brand_name': brandName!,
    if (shippingPreference != null)
      'shipping_preference': shippingPreference!.toJson(),
    if (landingPage != null) 'landing_page': landingPage!.toJson(),
    if (paymentMethodPreference != null)
      'payment_method_preference': paymentMethodPreference!.toJson(),
  };
}
