// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/paypal_v_2_payment_source_paypal.dart';

class PaypalV2PaymentSource {
  final PaypalV2PaymentSourcePaypal? paypal;

  PaypalV2PaymentSource({this.paypal});

  Map<String, dynamic> toJson() => {
    if (paypal != null) 'paypal': paypal!.toJson(),
  };
}
