// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

enum PaypalV2PaymentSourcePaypalExperienceContextLandingPage {
  LOGIN('LOGIN'),
  GUEST_CHECKOUT('GUEST_CHECKOUT'),
  NO_PREFERENCE('NO_PREFERENCE');

  final String _value;
  const PaypalV2PaymentSourcePaypalExperienceContextLandingPage(String value)
    : _value = value;
  String toJson() => _value;
}
