// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/paypal_v_2_payment_source_paypal_experience_context.dart';

class PaypalV2PaymentSourcePaypal {
  final PaypalV2PaymentSourcePaypalExperienceContext? experienceContext;

  PaypalV2PaymentSourcePaypal({this.experienceContext});

  Map<String, dynamic> toJson() => {
    if (experienceContext != null)
      'experience_context': experienceContext!.toJson(),
  };
}
