// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

enum PaypalV2PaymentSourcePaypalExperienceContextShippingPreference {
  GET_FROM_FILE('GET_FROM_FILE'),
  NO_SHIPPING('NO_SHIPPING'),
  SET_PROVIDED_ADDRESS('SET_PROVIDED_ADDRESS');

  final String _value;
  const PaypalV2PaymentSourcePaypalExperienceContextShippingPreference(
    String value,
  ) : _value = value;
  String toJson() => _value;
}
