// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_additional_data.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_payer.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_purchase_unit.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/paypal_v_2_payment_source.dart';

/// **Paypal bypass 파라미터**
class PaypalV2PaymentBypass {
  /// create order API 호출에 필요한 파라미터
  final List<PaypalV2PurchaseUnit>? purchaseUnits;
  final PaypalV2Payer? payer;
  final PaypalV2PaymentSource? paymentSource;

  /// STC 파라미터
  final List<PaypalV2AdditionalData>? additionalData;

  PaypalV2PaymentBypass({
    this.purchaseUnits,
    this.payer,
    this.paymentSource,
    this.additionalData,
  });

  Map<String, dynamic> toJson() => {
    if (purchaseUnits != null)
      'purchase_units': purchaseUnits!.map((e) => e.toJson()).toList(),
    if (payer != null) 'payer': payer!.toJson(),
    if (paymentSource != null) 'payment_source': paymentSource!.toJson(),
    if (additionalData != null)
      'additional_data': additionalData!.map((e) => e.toJson()).toList(),
  };

  static PaypalV2PaymentBypass fromJson(
    Map<String, dynamic> json,
  ) => PaypalV2PaymentBypass(
    purchaseUnits:
        (json['purchase_units'] as List?)
            ?.map((e) => PaypalV2PurchaseUnit.fromJson(e))
            .toList(),
    payer: json['payer'] != null ? PaypalV2Payer.fromJson(json['payer']) : null,
    paymentSource:
        json['payment_source'] != null
            ? PaypalV2PaymentSource.fromJson(json['payment_source'])
            : null,
    additionalData:
        (json['additional_data'] as List?)
            ?.map((e) => PaypalV2AdditionalData.fromJson(e))
            .toList(),
  );
}
