// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

enum PaypalV2PaymentSourcePaypalExperienceContextPaymentMethodPreference {
  UNRESTRICTED('UNRESTRICTED'),
  IMMEDIATE_PAYMENT_REQUIRED('IMMEDIATE_PAYMENT_REQUIRED');

  final String _value;
  const PaypalV2PaymentSourcePaypalExperienceContextPaymentMethodPreference(
    String value,
  ) : _value = value;
  String toJson() => _value;
  static PaypalV2PaymentSourcePaypalExperienceContextPaymentMethodPreference
  fromJson(String value) => values.firstWhere((e) => e._value == value);
}
