// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 해외 카드만 결제를 허용할지 여부(기본값: `"KR"`)
///
/// `"KR"`, `"EN"` 중 하나의 값으로 입력해주세요.
enum SmartroV2OpenType {
  KR('KR'),
  EN('EN');

  final String _value;
  const SmartroV2OpenType(String value) : _value = value;
  String toJson() => _value;
}
