// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/smartro_v_2_open_type.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/smartro_v_2_skin_color.dart';

/// 스마트로 V2 bypass 파라미터
class SmartroV2PaymentBypass {
  /// 결제 상품 품목 개수
  final int? goodsCnt;

  /// UI 스타일 (기본값: `"RED"`)
  ///
  /// `"RED"`, `"GREEN"`, `"BLUE"`, `"PURPLE"` 중 하나의 값으로 입력해주세요.
  final SmartroV2SkinColor? skinColor;

  /// 해외 카드만 결제를 허용할지 여부(기본값: `"KR"`)
  ///
  /// `"KR"`, `"EN"` 중 하나의 값으로 입력해주세요.
  final SmartroV2OpenType? openType;

  SmartroV2PaymentBypass({this.goodsCnt, this.skinColor, this.openType});

  Map<String, dynamic> toJson() => {
    if (goodsCnt != null) 'GoodsCnt': goodsCnt!,
    if (skinColor != null) 'SkinColor': skinColor!.toJson(),
    if (openType != null) 'OpenType': openType!.toJson(),
  };
}
