// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/tosspay_v_2_cash_receipt_trade_option.dart';

/// 토스페이 bypass 파라미터
class TosspayV2PaymentBypass {
  /// 결제 만료 기한 (yyyy-MM-dd HH:mm:ss)
  final String? expiredTime;

  /// 현금영수증 발급타입
  ///
  /// - CULTURE: 문화비
  /// - GENERAL: 일반 (기본값)
  /// - PUBLIC\_TP: 교통비
  final TosspayV2CashReceiptTradeOption? cashReceiptTradeOption;

  TosspayV2PaymentBypass({this.expiredTime, this.cashReceiptTradeOption});

  Map<String, dynamic> toJson() => {
    if (expiredTime != null) 'expiredTime': expiredTime!,
    if (cashReceiptTradeOption != null)
      'cashReceiptTradeOption': cashReceiptTradeOption!.toJson(),
  };
}
