// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 위젯에 보여줄 결제 수단. 예) 카드 전달시 등록한 결제 수단 중 카드만 노출 됨
enum TossBrandpayWidgetOptionsMethodType {
  CARD('카드'),
  ACCOUNT('계좌');

  final String _value;
  const TossBrandpayWidgetOptionsMethodType(String value) : _value = value;
  String toJson() => _value;
}
