// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_brandpay_options.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_widget_options.dart';

/// 토스 브랜드페이 bypass 파라미터
class TossBrandpayPaymentBypass {
  /// loadBrandpay 호출시 전달하는 세번째 파라미터
  final TossBrandpayBrandpayOptions? brandpayOptions;

  /// 브랜드페이 위젯 render() 함수 호출시 전달하는 두번째 파라미터
  final TossBrandpayWidgetOptions? widgetOptions;

  /// 카드사 할인코드
  final String? discountCode;

  /// 등록되어 있는 결제수단 중 하나를 지정해서 바로 결제하고 싶을 때 사용
  final String? methodId;

  TossBrandpayPaymentBypass({
    this.brandpayOptions,
    this.widgetOptions,
    this.discountCode,
    this.methodId,
  });

  Map<String, dynamic> toJson() => {
    if (brandpayOptions != null) 'brandpayOptions': brandpayOptions!.toJson(),
    if (widgetOptions != null) 'widgetOptions': widgetOptions!.toJson(),
    if (discountCode != null) 'discountCode': discountCode!,
    if (methodId != null) 'methodId': methodId!,
  };

  static TossBrandpayPaymentBypass fromJson(Map<String, dynamic> json) =>
      TossBrandpayPaymentBypass(
        brandpayOptions:
            json['brandpayOptions'] != null
                ? TossBrandpayBrandpayOptions.fromJson(json['brandpayOptions'])
                : null,
        widgetOptions:
            json['widgetOptions'] != null
                ? TossBrandpayWidgetOptions.fromJson(json['widgetOptions'])
                : null,
        discountCode: json['discountCode'] as String?,
        methodId: json['methodId'] as String?,
      );
}
