// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 현금영수증 발급타입
///
/// - CULTURE: 문화비
/// - GENERAL: 일반 (기본값)
/// - PUBLIC\_TP: 교통비
enum TosspayV2CashReceiptTradeOption {
  /// 문화비
  CULTURE('CULTURE'),

  /// 일반 (기본값)
  GENERAL('GENERAL'),

  /// 교통비
  PUBLIC_TP('PUBLIC_TP');

  final String _value;
  const TosspayV2CashReceiptTradeOption(String value) : _value = value;
  String toJson() => _value;
  static TosspayV2CashReceiptTradeOption fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
