// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 토스페이먼츠 bypass 파라미터
class TosspaymentsPaymentBypass {
  /// 토스페이먼츠 <-> 고객사 계약에 따라 프로모션 적용이 가능한 코드
  final String? discountCode;

  /// 해외 카드로만 결제가 가능하도록 할 지 여부
  final bool? useInternationalCardOnly;

  TosspaymentsPaymentBypass({this.discountCode, this.useInternationalCardOnly});

  Map<String, dynamic> toJson() => {
    if (discountCode != null) 'discountCode': discountCode!,
    if (useInternationalCardOnly != null)
      'useInternationalCardOnly': useInternationalCardOnly!,
  };
}
