// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_brandpay_options_ui.dart';

/// loadBrandpay 호출시 전달하는 세번째 파라미터
class TossBrandpayBrandpayOptions {
  final TossBrandpayBrandpayOptionsUi? ui;

  TossBrandpayBrandpayOptions({this.ui});

  Map<String, dynamic> toJson() => {if (ui != null) 'ui': ui!.toJson()};

  static TossBrandpayBrandpayOptions fromJson(Map<String, dynamic> json) =>
      TossBrandpayBrandpayOptions(
        ui:
            json['ui'] != null
                ? TossBrandpayBrandpayOptionsUi.fromJson(json['ui'])
                : null,
      );
}
