// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/tosspayments_paypal_shipping.dart';

/// 판매자 보호/위험 관리 파라미터
class TosspaymentsPaypal {
  final TosspaymentsPaypalShipping? shipping;

  /// 페이팔 STC로 전달되어 부정거래/리스크 평가에 활용됩니다.
  /// 키 정의는 [페이팔 STC 문서](https://static.tosspayments.com/public/STC.pdf)를 참고하세요.
  final Object? setTransactionContext;

  TosspaymentsPaypal({this.shipping, this.setTransactionContext});

  Map<String, dynamic> toJson() => {
    if (shipping != null) 'shipping': shipping!.toJson(),
    if (setTransactionContext != null)
      'setTransactionContext': setTransactionContext!,
  };
}
