// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class TosspaymentsPaypalShippingAddress {
  /// 국가 코드 (ISO-3166 alpha-2, 예: "US")
  final String country;

  /// 도로명/건물/번지
  final String? line1;

  /// 상세 주소
  final String? line2;

  /// 주/도 (예: "CA")
  final String? area1;

  /// 도시명 (예: "San Jose")
  final String area2;

  /// 우편번호 (중국, 일본, 프랑스, 독일 등은 필수)
  final String? postalCode;

  TosspaymentsPaypalShippingAddress({
    required this.country,
    this.line1,
    this.line2,
    this.area1,
    required this.area2,
    this.postalCode,
  });

  Map<String, dynamic> toJson() => {
    'country': country,
    if (line1 != null) 'line1': line1!,
    if (line2 != null) 'line2': line2!,
    if (area1 != null) 'area1': area1!,
    'area2': area2,
    if (postalCode != null) 'postalCode': postalCode!,
  };
}
