// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class TossBrandpayWidgetOptionsUiPromotionSectionSummary {
  /// 혜택 배지 영역을 보여줄지 여부. 혜택 배지 영역에서는 즉시 할인 대상 카드 정보 등을 간략히 보여 줌. 기본값은 true
  final bool? visible;

  TossBrandpayWidgetOptionsUiPromotionSectionSummary({this.visible});

  Map<String, dynamic> toJson() => {if (visible != null) 'visible': visible!};

  static TossBrandpayWidgetOptionsUiPromotionSectionSummary fromJson(
    Map<String, dynamic> json,
  ) => TossBrandpayWidgetOptionsUiPromotionSectionSummary(
    visible: json['visible'] as bool?,
  );
}
