// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_brandpay_options_ui_button_style.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_brandpay_options_ui_labels.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_brandpay_options_ui_navigation_bar.dart';

class TossBrandpayBrandpayOptionsUi {
  /// UI의 메인 색상. (기본값: #3182f6)
  final String? highlightColor;

  /// 버튼 스타일
  ///
  /// - default(기본값): 모서리가 둥글고 주변에 여백을 가진 버튼
  /// - full: 하단 영역이 전부 채워지는 형태의 버튼
  final TossBrandpayBrandpayOptionsUiButtonStyle? buttonStyle;
  final TossBrandpayBrandpayOptionsUiLabels? labels;
  final TossBrandpayBrandpayOptionsUiNavigationBar? navigationBar;

  TossBrandpayBrandpayOptionsUi({
    this.highlightColor,
    this.buttonStyle,
    this.labels,
    this.navigationBar,
  });

  Map<String, dynamic> toJson() => {
    if (highlightColor != null) 'highlightColor': highlightColor!,
    if (buttonStyle != null) 'buttonStyle': buttonStyle!.toJson(),
    if (labels != null) 'labels': labels!.toJson(),
    if (navigationBar != null) 'navigationBar': navigationBar!.toJson(),
  };
}
