// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class TossBrandpayWidgetOptionsUiPromotionSectionDescription {
  /// 결제 혜택 영역을 보여줄지 여부. 기본값은 true
  final bool? visible;

  /// 결제 혜택의 상세 설명을 보여줄지 여부. 각 카드사의 결제 혜택을 자세히 설명 함. 기본값은 false
  final bool? defaultOpen;

  TossBrandpayWidgetOptionsUiPromotionSectionDescription({
    this.visible,
    this.defaultOpen,
  });

  Map<String, dynamic> toJson() => {
    if (visible != null) 'visible': visible!,
    if (defaultOpen != null) 'defaultOpen': defaultOpen!,
  };

  static TossBrandpayWidgetOptionsUiPromotionSectionDescription fromJson(
    Map<String, dynamic> json,
  ) => TossBrandpayWidgetOptionsUiPromotionSectionDescription(
    visible: json['visible'] as bool?,
    defaultOpen: json['defaultOpen'] as bool?,
  );
}
