// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/tosspayments_paypal_shipping_address.dart';

class TosspaymentsPaypalShipping {
  /// 구매자 전체 이름
  final String? fullName;
  final TosspaymentsPaypalShippingAddress address;

  TosspaymentsPaypalShipping({this.fullName, required this.address});

  Map<String, dynamic> toJson() => {
    if (fullName != null) 'fullName': fullName!,
    'address': address.toJson(),
  };
}
