// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_widget_options_ui_promotion_section.dart';

class TossBrandpayWidgetOptionsUi {
  final TossBrandpayWidgetOptionsUiPromotionSection? promotionSection;

  TossBrandpayWidgetOptionsUi({this.promotionSection});

  Map<String, dynamic> toJson() => {
    if (promotionSection != null)
      'promotionSection': promotionSection!.toJson(),
  };

  static TossBrandpayWidgetOptionsUi fromJson(Map<String, dynamic> json) =>
      TossBrandpayWidgetOptionsUi(
        promotionSection:
            json['promotionSection'] != null
                ? TossBrandpayWidgetOptionsUiPromotionSection.fromJson(
                  json['promotionSection'],
                )
                : null,
      );
}
