// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_widget_options_method_type.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_widget_options_ui.dart';

/// 브랜드페이 위젯 render() 함수 호출시 전달하는 두번째 파라미터
class TossBrandpayWidgetOptions {
  /// 위젯에 보여줄 결제 수단. 예) 카드 전달시 등록한 결제 수단 중 카드만 노출 됨
  final TossBrandpayWidgetOptionsMethodType? methodType;

  /// 위젯에서 기본 결제 수단으로 선택할 결제 수단의 ID
  final String? methodId;
  final TossBrandpayWidgetOptionsUi? ui;

  TossBrandpayWidgetOptions({this.methodType, this.methodId, this.ui});

  Map<String, dynamic> toJson() => {
    if (methodType != null) 'methodType': methodType!.toJson(),
    if (methodId != null) 'methodId': methodId!,
    if (ui != null) 'ui': ui!.toJson(),
  };
}
