// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class TossBrandpayBrandpayOptionsUiNavigationBar {
  /// 내비게이션 바 사용 여부. (기본값: true)
  final bool? visible;

  /// 내비게이션 바 위쪽에 설정할 여백 값. 값의 단위는 px
  final int? paddingTop;

  TossBrandpayBrandpayOptionsUiNavigationBar({this.visible, this.paddingTop});

  Map<String, dynamic> toJson() => {
    if (visible != null) 'visible': visible!,
    if (paddingTop != null) 'paddingTop': paddingTop!,
  };

  static TossBrandpayBrandpayOptionsUiNavigationBar fromJson(
    Map<String, dynamic> json,
  ) => TossBrandpayBrandpayOptionsUiNavigationBar(
    visible: json['visible'] as bool?,
    paddingTop: json['paddingTop'] as int?,
  );
}
