// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_widget_options_ui_promotion_section_description.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay_widget_options_ui_promotion_section_summary.dart';

class TossBrandpayWidgetOptionsUiPromotionSection {
  final TossBrandpayWidgetOptionsUiPromotionSectionSummary? summary;
  final TossBrandpayWidgetOptionsUiPromotionSectionDescription? description;

  TossBrandpayWidgetOptionsUiPromotionSection({this.summary, this.description});

  Map<String, dynamic> toJson() => {
    if (summary != null) 'summary': summary!.toJson(),
    if (description != null) 'description': description!.toJson(),
  };

  static TossBrandpayWidgetOptionsUiPromotionSection fromJson(
    Map<String, dynamic> json,
  ) => TossBrandpayWidgetOptionsUiPromotionSection(
    summary:
        json['summary'] != null
            ? TossBrandpayWidgetOptionsUiPromotionSectionSummary.fromJson(
              json['summary'],
            )
            : null,
    description:
        json['description'] != null
            ? TossBrandpayWidgetOptionsUiPromotionSectionDescription.fromJson(
              json['description'],
            )
            : null,
  );
}
