// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class TossBrandpayBrandpayOptionsUiLabels {
  /// UI에 표시되는 원터치 결제를 대신해 사용할 텍스트. (기본값: "원터치 결제")
  final String? oneTouchPay;

  TossBrandpayBrandpayOptionsUiLabels({this.oneTouchPay});

  Map<String, dynamic> toJson() => {
    if (oneTouchPay != null) 'oneTouchPay': oneTouchPay!,
  };
}
