// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **단독 노출할 인증 업체 코드**
///
/// 인증 업체 선택 화면 없이 설정한 인증 업체를 통해 인증하도록 합니다.
enum InicisUnifiedDirectAgency {
  /// 페이코
  PAYCO('PAYCO'),

  /// 패스 (통신사)
  PASS('PASS'),

  /// 토스
  TOSS('TOSS'),

  /// 금융결제원
  KFTC('KFTC'),

  /// 카카오
  KAKAO('KAKAO'),

  /// 네이버
  NAVER('NAVER'),

  /// 삼성패스
  SAMSUNG('SAMSUNG'),

  /// 신한은행
  SHINHAN('SHINHAN'),

  /// 국민은행
  KB('KB'),

  /// 하나은행
  HANA('HANA'),

  /// 우리은행
  WOORI('WOORI'),

  /// 농협은행
  NH('NH'),

  /// 카카오뱅크
  KAKAOBANK('KAKAOBANK'),

  /// 휴대폰 인증, 별도 계약 필요
  SMS('SMS');

  final String _value;
  const InicisUnifiedDirectAgency(String value) : _value = value;
  String toJson() => _value;
  static InicisUnifiedDirectAgency fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
