// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **KCP bypass 파라미터**
class KcpV2IdentityVerificationBypass {
  /// **DI 생성 시 사용할 사이트 ID**
  final String? webSiteid;

  KcpV2IdentityVerificationBypass({this.webSiteid});

  Map<String, dynamic> toJson() => {
    if (webSiteid != null) 'web_siteid': webSiteid!,
  };

  static KcpV2IdentityVerificationBypass fromJson(Map<String, dynamic> json) =>
      KcpV2IdentityVerificationBypass(webSiteid: json['web_siteid'] as String?);
}
