// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2_style_color.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2_style_label.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2_style_layout.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2_style_shape.dart';

/// 페이팔 빌링키 발급 UI 호출 시 필요한 파라미터
class PaypalV2Style {
  /// 버튼 색상
  final PaypalV2StyleColor? color;

  /// 버튼 높이
  final int? height;

  /// 버튼 라벨
  final PaypalV2StyleLabel? label;

  /// 버튼 렌더링 방향
  final PaypalV2StyleLayout? layout;

  /// 버튼 모양
  final PaypalV2StyleShape? shape;

  /// 버튼 하위에 문구 노출 여부
  final bool? tagline;

  PaypalV2Style({
    this.color,
    this.height,
    this.label,
    this.layout,
    this.shape,
    this.tagline,
  });

  Map<String, dynamic> toJson() => {
    if (color != null) 'color': color!.toJson(),
    if (height != null) 'height': height!,
    if (label != null) 'label': label!.toJson(),
    if (layout != null) 'layout': layout!.toJson(),
    if (shape != null) 'shape': shape!.toJson(),
    if (tagline != null) 'tagline': tagline!,
  };

  static PaypalV2Style fromJson(Map<String, dynamic> json) => PaypalV2Style(
    color:
        json['color'] != null
            ? PaypalV2StyleColor.fromJson(json['color'])
            : null,
    height: json['height'] as int?,
    label:
        json['label'] != null
            ? PaypalV2StyleLabel.fromJson(json['label'])
            : null,
    layout:
        json['layout'] != null
            ? PaypalV2StyleLayout.fromJson(json['layout'])
            : null,
    shape:
        json['shape'] != null
            ? PaypalV2StyleShape.fromJson(json['shape'])
            : null,
    tagline: json['tagline'] as bool?,
  );
}
