// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2_additional_data.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2_shipping_address.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2_style.dart';

/// **Paypal bypass 파라미터**
class PaypalV2LoadIssueBillingKeyUIBypass {
  /// 페이팔 빌링키 발급 UI 호출 시 필요한 파라미터
  final PaypalV2Style? style;
  final PaypalV2ShippingAddress? shippingAddress;

  /// STC 파라미터
  final List<PaypalV2AdditionalData>? additionalData;

  PaypalV2LoadIssueBillingKeyUIBypass({
    this.style,
    this.shippingAddress,
    this.additionalData,
  });

  Map<String, dynamic> toJson() => {
    if (style != null) 'style': style!.toJson(),
    if (shippingAddress != null) 'shipping_address': shippingAddress!.toJson(),
    if (additionalData != null)
      'additional_data': additionalData!.map((e) => e.toJson()).toList(),
  };

  static PaypalV2LoadIssueBillingKeyUIBypass fromJson(
    Map<String, dynamic> json,
  ) => PaypalV2LoadIssueBillingKeyUIBypass(
    style: json['style'] != null ? PaypalV2Style.fromJson(json['style']) : null,
    shippingAddress:
        json['shipping_address'] != null
            ? PaypalV2ShippingAddress.fromJson(json['shipping_address'])
            : null,
    additionalData:
        (json['additional_data'] as List?)
            ?.map((e) => PaypalV2AdditionalData.fromJson(e))
            .toList(),
  );
}
