// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2_country.dart';

class PaypalV2ShippingAddress {
  /// 수령인 이름
  final String? recipientName;

  /// 도로명 주소
  final String line1;

  /// 아파트 동 호수
  final String? line2;

  /// 도시 이름
  final String city;

  /// 주 이름 (아르헨티나, 브라질, 캐나다, 중국, 인도, 이탈리아, 일본, 멕시코, 태국 또는 미국의 경우 필수)
  final String? state;

  /// 우편번호
  final String? postalCode;

  /// **페이팔 V2 국가 코드**
  final PaypalV2Country countryCode;

  PaypalV2ShippingAddress({
    this.recipientName,
    required this.line1,
    this.line2,
    required this.city,
    this.state,
    this.postalCode,
    required this.countryCode,
  });

  Map<String, dynamic> toJson() => {
    if (recipientName != null) 'recipient_name': recipientName!,
    'line1': line1,
    if (line2 != null) 'line2': line2!,
    'city': city,
    if (state != null) 'state': state!,
    if (postalCode != null) 'postal_code': postalCode!,
    'country_code': countryCode.toJson(),
  };

  static PaypalV2ShippingAddress fromJson(Map<String, dynamic> json) =>
      PaypalV2ShippingAddress(
        recipientName: json['recipient_name'] as String?,
        line1: json['line1'] as String,
        line2: json['line2'] as String?,
        city: json['city'] as String,
        state: json['state'] as String?,
        postalCode: json['postal_code'] as String?,
        countryCode: PaypalV2Country.fromJson(json['country_code']),
      );
}
