// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 버튼 렌더링 방향
enum PaypalV2StyleLayout {
  vertical('vertical'),
  horizontal('horizontal');

  final String _value;
  const PaypalV2StyleLayout(String value) : _value = value;
  String toJson() => _value;
  static PaypalV2StyleLayout fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
