// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class PaypalV2AdditionalData {
  final String key;
  final String value;

  PaypalV2AdditionalData({required this.key, required this.value});

  Map<String, dynamic> toJson() => {'key': key, 'value': value};

  static PaypalV2AdditionalData fromJson(Map<String, dynamic> json) =>
      PaypalV2AdditionalData(
        key: json['key'] as String,
        value: json['value'] as String,
      );
}
