// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/identity_verification/danal.dart';
import 'package:portone_flutter/v2/model/entity/bypass/identity_verification/inicis_unified.dart';
import 'package:portone_flutter/v2/model/entity/bypass/identity_verification/kcp_v_2.dart';

/// **PG사 본인인증 창 호출 시 PG사로 그대로 bypass할 값들의 모음**
class IdentityVerificationBypass {
  /// **다날 bypass 파라미터**
  final DanalIdentityVerificationBypass? danal;

  /// **KG이니시스 bypass 파라미터**
  final InicisUnifiedIdentityVerificationBypass? inicisUnified;

  /// **KCP bypass 파라미터**
  final KcpV2IdentityVerificationBypass? kcpV2;

  IdentityVerificationBypass({this.danal, this.inicisUnified, this.kcpV2});

  Map<String, dynamic> toJson() => {
    if (danal != null) 'danal': danal!.toJson(),
    if (inicisUnified != null) 'inicisUnified': inicisUnified!.toJson(),
    if (kcpV2 != null) 'kcpV2': kcpV2!.toJson(),
  };
}
