// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/galaxia.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/inicis_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/kcp_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/naverpay.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/smartro_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/tosspay_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key/welcome.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/kakaopay.dart';

class IssueBillingKeyBypass {
  /// **KG이니시스 bypass 파라미터**
  final InicisV2IssueBillingKeyBypass? inicisV2;

  /// **KCP bypass 파라미터**
  final KcpV2IssueBillingKeyBypass? kcpV2;

  /// **스마트로 bypass 파라미터**
  final SmartroV2IssueBillingKeyBypass? smartroV2;

  /// **웰컴페이먼츠 bypass 파라미터**
  final WelcomeIssueBillingKeyBypass? welcome;

  /// **갤럭시아 bypass 파라미터**
  final GalaxiaIssueBillingKeyBypass? galaxia;

  /// **네이버페이 bypass 파라미터**
  final NaverpayIssueBillingKeyBypass? naverpay;

  /// 카카오페이 bypass 파라미터
  final KakaopayPaymentBypass? kakaopay;

  /// **토스페이 bypass 파라미터**
  final TosspayV2IssueBillingKeyBypass? tosspayV2;

  IssueBillingKeyBypass({
    this.inicisV2,
    this.kcpV2,
    this.smartroV2,
    this.welcome,
    this.galaxia,
    this.naverpay,
    this.kakaopay,
    this.tosspayV2,
  });

  Map<String, dynamic> toJson() => {
    if (inicisV2 != null) 'inicis_v2': inicisV2!.toJson(),
    if (kcpV2 != null) 'kcp_v2': kcpV2!.toJson(),
    if (smartroV2 != null) 'smartro_v2': smartroV2!.toJson(),
    if (welcome != null) 'welcome': welcome!.toJson(),
    if (galaxia != null) 'galaxia': galaxia!.toJson(),
    if (naverpay != null) 'naverpay': naverpay!.toJson(),
    if (kakaopay != null) 'kakaopay': kakaopay!.toJson(),
    if (tosspayV2 != null) 'tosspay_v2': tosspayV2!.toJson(),
  };
}
