// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key_and_pay/eximbay_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key_and_pay/galaxia.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key_and_pay/payletter_global.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key_and_pay/welcome.dart';

class IssueBillingKeyAndPayBypass {
  /// **웰컴페이먼츠 bypass 파라미터**
  final WelcomeIssueBillingKeyAndPayBypass? welcome;

  /// **페이레터 해외결제 bypass 파라미터**
  final PayletterGlobalIssueBillingKeyAndPayBypass? payletterGlobal;

  /// **엑심베이 bypass 파라미터**
  final EximbayV2IssueBillingKeyAndPayBypass? eximbayV2;

  /// **갤럭시아 bypass 파라미터**
  final GalaxiaIssueBillingKeyAndPayBypass? galaxia;

  IssueBillingKeyAndPayBypass({
    this.welcome,
    this.payletterGlobal,
    this.eximbayV2,
    this.galaxia,
  });

  Map<String, dynamic> toJson() => {
    if (welcome != null) 'welcome': welcome!.toJson(),
    if (payletterGlobal != null) 'payletter_global': payletterGlobal!.toJson(),
    if (eximbayV2 != null) 'eximbay_v2': eximbayV2!.toJson(),
    if (galaxia != null) 'galaxia': galaxia!.toJson(),
  };

  static IssueBillingKeyAndPayBypass fromJson(Map<String, dynamic> json) =>
      IssueBillingKeyAndPayBypass(
        welcome:
            json['welcome'] != null
                ? WelcomeIssueBillingKeyAndPayBypass.fromJson(json['welcome'])
                : null,
        payletterGlobal:
            json['payletter_global'] != null
                ? PayletterGlobalIssueBillingKeyAndPayBypass.fromJson(
                  json['payletter_global'],
                )
                : null,
        eximbayV2:
            json['eximbay_v2'] != null
                ? EximbayV2IssueBillingKeyAndPayBypass.fromJson(
                  json['eximbay_v2'],
                )
                : null,
        galaxia:
            json['galaxia'] != null
                ? GalaxiaIssueBillingKeyAndPayBypass.fromJson(json['galaxia'])
                : null,
      );
}
