// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui/paypal_v_2.dart';

class LoadIssueBillingKeyUIBypass {
  /// **Paypal bypass 파라미터**
  final PaypalV2LoadIssueBillingKeyUIBypass? paypalV2;

  LoadIssueBillingKeyUIBypass({this.paypalV2});

  Map<String, dynamic> toJson() => {
    if (paypalV2 != null) 'paypal_v2': paypalV2!.toJson(),
  };
}
