// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/payment/eximbay_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/galaxia.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/hyphen.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/inicis_jp.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/inicis_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/kakaopay.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/kcp_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/kpn.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/ksnet.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/mobilians_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/naverpay.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/nice_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/payletter_global.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/paypal_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/smartro_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/toss_brandpay.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/tosspay_v_2.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/tosspayments.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/triple_a.dart';
import 'package:portone_flutter/v2/model/entity/bypass/payment/welcome.dart';

/// **PG사 결제창 호출 시 PG사로 그대로 bypass할 값들의 모음**
class PaymentBypass {
  /// 토스페이먼츠 bypass 파라미터
  final TosspaymentsPaymentBypass? tosspayments;

  /// (신)나이스페이먼츠 bypass 파라미터
  final NiceV2PaymentBypass? niceV2;

  /// **Paypal bypass 파라미터**
  final PaypalV2PaymentBypass? paypalV2;

  /// KG이니시스 bypass 파라미터
  ///
  /// KG이니시스는 PC 결제 모듈과 모바일 결제 모듈이 분리되어 있기 때문에 bypass 파라미터 또한 PC용과 모바일용이 분리되어 있습니다.
  final InicisV2Bypass? inicisV2;

  /// NHN KCP bypass 파라미터
  final KcpV2Bypass? kcpV2;

  /// 스마트로 V2 bypass 파라미터
  final SmartroV2PaymentBypass? smartroV2;

  /// KSNET bypass 파라미터
  final KsnetPaymentBypass? ksnet;

  /// 웰컴페이먼츠 bypass 파라미터
  final WelcomePaymentBypass? welcome;

  /// KPN bypass 파라미터
  final KpnBypass? kpn;

  /// 네이버페이 bypass 파라미터
  final NaverpayPaymentBypass? naverpay;

  /// 카카오페이 bypass 파라미터
  final KakaopayPaymentBypass? kakaopay;

  /// 토스페이 bypass 파라미터
  final TosspayV2PaymentBypass? tosspayV2;

  /// 토스 브랜드페이 bypass 파라미터
  final TossBrandpayPaymentBypass? tossBrandpay;

  /// 하이픈 bypass 파라미터
  final HyphenBypass? hyphen;

  /// 엑심베이 V2 bypass 파라미터
  final EximbayV2Bypass? eximbayV2;

  /// 갤럭시아 bypass 파라미터
  final GalaxiaPaymentBypass? galaxia;

  /// 이니시스 일본 bypass 파라미터
  final InicisJpBypass? inicisJp;

  /// 페이레터 해외결제 bypass 파라미터
  final PayletterGlobalBypass? payletterGlobal;

  /// 모빌리언스 V2 bypass 파라미터
  final MobiliansV2Bypass? mobiliansV2;

  /// Triple-A bypass 파라미터
  final TripleABypass? tripleA;

  PaymentBypass({
    this.tosspayments,
    this.niceV2,
    this.paypalV2,
    this.inicisV2,
    this.kcpV2,
    this.smartroV2,
    this.ksnet,
    this.welcome,
    this.kpn,
    this.naverpay,
    this.kakaopay,
    this.tosspayV2,
    this.tossBrandpay,
    this.hyphen,
    this.eximbayV2,
    this.galaxia,
    this.inicisJp,
    this.payletterGlobal,
    this.mobiliansV2,
    this.tripleA,
  });

  Map<String, dynamic> toJson() => {
    if (tosspayments != null) 'tosspayments': tosspayments!.toJson(),
    if (niceV2 != null) 'nice_v2': niceV2!.toJson(),
    if (paypalV2 != null) 'paypal_v2': paypalV2!.toJson(),
    if (inicisV2 != null) 'inicis_v2': inicisV2!.toJson(),
    if (kcpV2 != null) 'kcp_v2': kcpV2!.toJson(),
    if (smartroV2 != null) 'smartro_v2': smartroV2!.toJson(),
    if (ksnet != null) 'ksnet': ksnet!.toJson(),
    if (welcome != null) 'welcome': welcome!.toJson(),
    if (kpn != null) 'kpn': kpn!.toJson(),
    if (naverpay != null) 'naverpay': naverpay!.toJson(),
    if (kakaopay != null) 'kakaopay': kakaopay!.toJson(),
    if (tosspayV2 != null) 'tosspay_v2': tosspayV2!.toJson(),
    if (tossBrandpay != null) 'toss_brandpay': tossBrandpay!.toJson(),
    if (hyphen != null) 'hyphen': hyphen!.toJson(),
    if (eximbayV2 != null) 'eximbay_v2': eximbayV2!.toJson(),
    if (galaxia != null) 'galaxia': galaxia!.toJson(),
    if (inicisJp != null) 'inicis_jp': inicisJp!.toJson(),
    if (payletterGlobal != null) 'payletter_global': payletterGlobal!.toJson(),
    if (mobiliansV2 != null) 'mobilians_v2': mobiliansV2!.toJson(),
    if (tripleA != null) 'triple_a': tripleA!.toJson(),
  };
}
