// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/card_company.dart';

class IssueBillingKeyRequestUnionCard {
  /// 카드 결제시 사용되는 카드사 코드
  final CardCompany? cardCompany;

  IssueBillingKeyRequestUnionCard({this.cardCompany});

  Map<String, dynamic> toJson() => {
    if (cardCompany != null) 'cardCompany': cardCompany!.toJson(),
  };

  static IssueBillingKeyRequestUnionCard fromJson(Map<String, dynamic> json) =>
      IssueBillingKeyRequestUnionCard(
        cardCompany:
            json['cardCompany'] != null
                ? CardCompany.fromJson(json['cardCompany'])
                : null,
      );
}
