// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/carrier.dart';

class IssueBillingKeyAndPayRequestUnionMobile {
  /// 통신사 코드
  final Carrier? carrier;
  final List<Carrier>? avaliableCarriers;

  IssueBillingKeyAndPayRequestUnionMobile({
    this.carrier,
    this.avaliableCarriers,
  });

  Map<String, dynamic> toJson() => {
    if (carrier != null) 'carrier': carrier!.toJson(),
    if (avaliableCarriers != null)
      'avaliableCarriers': avaliableCarriers!.map((e) => e.toJson()).toList(),
  };
}
