// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/carrier.dart';

class IssueBillingKeyRequestUnionMobile {
  /// 통신사 코드
  final Carrier? carrier;
  final List<Carrier>? avaliableCarriers;

  IssueBillingKeyRequestUnionMobile({this.carrier, this.avaliableCarriers});

  Map<String, dynamic> toJson() => {
    if (carrier != null) 'carrier': carrier!.toJson(),
    if (avaliableCarriers != null)
      'avaliableCarriers': avaliableCarriers!.map((e) => e.toJson()).toList(),
  };

  static IssueBillingKeyRequestUnionMobile fromJson(
    Map<String, dynamic> json,
  ) => IssueBillingKeyRequestUnionMobile(
    carrier: json['carrier'] != null ? Carrier.fromJson(json['carrier']) : null,
    avaliableCarriers:
        (json['avaliableCarriers'] as List?)
            ?.map((e) => Carrier.fromJson(e))
            .toList(),
  );
}
