// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/billing_key_method.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key_bypass.dart';
import 'package:portone_flutter/v2/model/entity/currency.dart';
import 'package:portone_flutter/v2/model/entity/customer.dart';
import 'package:portone_flutter/v2/model/entity/iframe.dart';
import 'package:portone_flutter/v2/model/entity/locale.dart';
import 'package:portone_flutter/v2/model/entity/offer_period.dart';
import 'package:portone_flutter/v2/model/entity/popup.dart';
import 'package:portone_flutter/v2/model/entity/product_type.dart';
import 'package:portone_flutter/v2/model/entity/window_types.dart';
import 'package:portone_flutter/v2/model/request/issue_billing_key_request_union_card.dart';
import 'package:portone_flutter/v2/model/request/issue_billing_key_request_union_easy_pay.dart';
import 'package:portone_flutter/v2/model/request/issue_billing_key_request_union_mobile.dart';
import 'package:portone_flutter/v2/model/request/issue_billing_key_request_union_paypal.dart';

class IssueBillingKeyRequest {
  /// 빌링키 발급 창에 디스플레이 용으로 띄우는 금액
  final int? displayAmount;

  /// **화폐**
  ///
  /// [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) 화폐 코드
  ///
  /// 대한민국 원, 일본 엔이 아닌 화폐를 사용할 때에는 금액을 minor unit 단위로 입력해야 함에 유의하세요.
  final Currency? currency;

  /// **상점 아이디**
  ///
  /// 포트원 계정에 생성된 상점을 식별하는 고유한 값으로 [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel) 우측 상단에서 확인할 수 있습니다.
  final String storeId;

  /// **채널 키**
  ///
  /// 포트원에 등록된 결제 채널 중 하나를 지정합니다.
  ///
  /// [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel)에서 채널 연동 후 채널 키를 확인할 수 있습니다.
  ///
  /// 채널 키와 채널 그룹 ID 중 하나를 지정해야 합니다.
  final String? channelKey;

  /// 빌링키 발급 수단
  final BillingKeyMethod billingKeyMethod;

  /// 빌링키 발급 주문 명
  final String? issueName;

  /// 빌링키 발급 주문 고유 번호
  final String? issueId;
  final Customer? customer;

  /// **환경 별 제공되는 결제/본인인증 창 유형**
  ///
  /// - PG사에 따라 가능한 창 유형이 다릅니다.
  /// - 전달되지 않았을 때 결정되는 기본 창이 다릅니다.
  /// - 미입력 시, 해당 PG사의 기본 창 방식을 따릅니다.
  final WindowTypes? windowType;

  /// **결과 리턴 방식을 리디렉션으로 강제**
  ///
  /// `true`로 설정하면 원래 프로미스로 resolve 되었을 상황에서도
  /// `redirectUrl`로 쿼리 파라미터와 함께 리디렉션합니다.
  ///
  /// - `redirectUrl`이 없으면 기존처럼 프로미스로 반환합니다.
  /// - 빌링키 발급 시작 전 발생하는 에러는 리디렉션하지 않습니다.
  final bool? forceRedirect;

  /// **UI 언어**
  ///
  /// KG이니시스, 스마트로, KSNET, 웰컴페이먼츠 (PC), 한국결제네트웍스, 엑심베이, Triple-A에서 설정 가능하며, PG마다 지원하는 언어 목록은 차이가 있습니다.
  final Locale? locale;

  /// **빌링키 발급 정보와 함께 관리하고 싶은 고객사 커스텀 JSON 데이터**
  final Object? customData;

  /// **서비스 제공 기간**
  ///
  /// range와 interval 중 하나를 입력해주세요.
  ///
  /// - range: 제공 기간 범위
  /// - interval: 제공 기간 주기
  ///
  /// 예1) 2023년 1월 1일 00시 00분 00초(KST) ~
  ///
  /// ```js
  /// range: {
  /// from: '2023-01-01T00:00:00+09:00'
  /// }
  /// ```
  ///
  /// 예2) ~ 2023년 1월 1일 00시 00분 00초(KST)
  ///
  /// ```js
  /// range: {
  /// to: '2023-01-01T00:00:00+09:00'
  /// }
  /// ```
  ///
  /// 예3) 2023년 1월 1일 00시 00분 00초(KST) ~ 2023년 12월 31일 23시 59분 59초(KST)
  ///
  /// ```js
  /// range: {
  /// from: '2023-12-31T23:59:59+09:00'
  /// to: '2023-01-01T00:00:00+09:00'
  /// }
  /// ```
  ///
  /// 예4) 30일 주기
  /// `interval: '30d'`
  ///
  /// 예5) 6개월 주기
  /// `interval: '6m'`
  ///
  /// 예6) 1년 주기
  /// `interval: '1y'`
  final OfferPeriod? offerPeriod;

  /// 앱 URL Scheme
  final String appScheme;

  /// 웹훅 URL
  final List<String>? noticeUrls;

  /// **상품 유형**
  final ProductType? productType;
  final IssueBillingKeyBypass? bypass;

  /// **팝업 관련 필드**
  ///
  /// UI가 팝업 창으로 열릴 때 적용되는 속성입니다.
  final Popup? popup;

  /// **결제창이 iframe 방식일 경우 결제창에 적용할 속성**
  final Iframe? iframe;
  final IssueBillingKeyRequestUnionCard? card;
  final IssueBillingKeyRequestUnionMobile? mobile;
  final IssueBillingKeyRequestUnionEasyPay? easyPay;
  final IssueBillingKeyRequestUnionPaypal? paypal;

  IssueBillingKeyRequest({
    this.displayAmount,
    this.currency,
    required this.storeId,
    this.channelKey,
    required this.billingKeyMethod,
    this.issueName,
    this.issueId,
    this.customer,
    this.windowType,
    this.forceRedirect,
    this.locale,
    this.customData,
    this.offerPeriod,
    required this.appScheme,
    this.noticeUrls,
    this.productType,
    this.bypass,
    this.popup,
    this.iframe,
    this.card,
    this.mobile,
    this.easyPay,
    this.paypal,
  });

  Map<String, dynamic> toJson() => {
    if (displayAmount != null) 'displayAmount': displayAmount!,
    if (currency != null) 'currency': currency!.toJson(),
    'storeId': storeId,
    if (channelKey != null) 'channelKey': channelKey!,
    'billingKeyMethod': billingKeyMethod.toJson(),
    if (issueName != null) 'issueName': issueName!,
    if (issueId != null) 'issueId': issueId!,
    if (customer != null) 'customer': customer!.toJson(),
    if (windowType != null) 'windowType': windowType!.toJson(),
    if (forceRedirect != null) 'forceRedirect': forceRedirect!,
    if (locale != null) 'locale': locale!.toJson(),
    if (customData != null) 'customData': customData!,
    if (offerPeriod != null) 'offerPeriod': offerPeriod!.toJson(),
    'appScheme': appScheme,
    if (noticeUrls != null) 'noticeUrls': noticeUrls!,
    if (productType != null) 'productType': productType!.toJson(),
    if (bypass != null) 'bypass': bypass!.toJson(),
    if (popup != null) 'popup': popup!.toJson(),
    if (iframe != null) 'iframe': iframe!.toJson(),
    if (card != null) 'card': card!.toJson(),
    if (mobile != null) 'mobile': mobile!.toJson(),
    if (easyPay != null) 'easyPay': easyPay!.toJson(),
    if (paypal != null) 'paypal': paypal!.toJson(),
  };

  static IssueBillingKeyRequest fromJson(
    Map<String, dynamic> json,
  ) => IssueBillingKeyRequest(
    displayAmount: json['displayAmount'] as int?,
    currency:
        json['currency'] != null ? Currency.fromJson(json['currency']) : null,
    storeId: json['storeId'] as String,
    channelKey: json['channelKey'] as String?,
    billingKeyMethod: BillingKeyMethod.fromJson(json['billingKeyMethod']),
    issueName: json['issueName'] as String?,
    issueId: json['issueId'] as String?,
    customer:
        json['customer'] != null ? Customer.fromJson(json['customer']) : null,
    windowType:
        json['windowType'] != null
            ? WindowTypes.fromJson(json['windowType'])
            : null,
    forceRedirect: json['forceRedirect'] as bool?,
    locale: json['locale'] != null ? Locale.fromJson(json['locale']) : null,
    customData: json['customData'],
    offerPeriod:
        json['offerPeriod'] != null
            ? OfferPeriod.fromJson(json['offerPeriod'])
            : null,
    appScheme: json['appScheme'] as String,
    noticeUrls: (json['noticeUrls'] as List?)?.cast<String>(),
    productType:
        json['productType'] != null
            ? ProductType.fromJson(json['productType'])
            : null,
    bypass:
        json['bypass'] != null
            ? IssueBillingKeyBypass.fromJson(json['bypass'])
            : null,
    popup: json['popup'] != null ? Popup.fromJson(json['popup']) : null,
    iframe: json['iframe'] != null ? Iframe.fromJson(json['iframe']) : null,
    card:
        json['card'] != null
            ? IssueBillingKeyRequestUnionCard.fromJson(json['card'])
            : null,
    mobile:
        json['mobile'] != null
            ? IssueBillingKeyRequestUnionMobile.fromJson(json['mobile'])
            : null,
    easyPay:
        json['easyPay'] != null
            ? IssueBillingKeyRequestUnionEasyPay.fromJson(json['easyPay'])
            : null,
    paypal:
        json['paypal'] != null
            ? IssueBillingKeyRequestUnionPaypal.fromJson(json['paypal'])
            : null,
  );
}
