// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/billing_key_and_pay_method.dart';
import 'package:portone_flutter/v2/model/entity/bypass/issue_billing_key_and_pay_bypass.dart';
import 'package:portone_flutter/v2/model/entity/country.dart';
import 'package:portone_flutter/v2/model/entity/currency.dart';
import 'package:portone_flutter/v2/model/entity/customer.dart';
import 'package:portone_flutter/v2/model/entity/iframe.dart';
import 'package:portone_flutter/v2/model/entity/locale.dart';
import 'package:portone_flutter/v2/model/entity/offer_period.dart';
import 'package:portone_flutter/v2/model/entity/popup.dart';
import 'package:portone_flutter/v2/model/entity/product.dart';
import 'package:portone_flutter/v2/model/entity/product_type.dart';
import 'package:portone_flutter/v2/model/entity/store_details.dart';
import 'package:portone_flutter/v2/model/entity/window_types.dart';
import 'package:portone_flutter/v2/model/request/issue_billing_key_and_pay_request_union_mobile.dart';

class IssueBillingKeyAndPayRequest {
  /// **상점 아이디**
  ///
  /// 포트원 계정에 생성된 상점을 식별하는 고유한 값으로 [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel) 우측 상단에서 확인할 수 있습니다.
  final String storeId;

  /// **결제 ID**
  ///
  /// 고객사에서 임의로 ID를 정합니다.
  ///
  /// 이미 결제 완료된 `paymentId`로 결제를 요청하는 경우 실패합니다.
  final String paymentId;

  /// **주문명**
  final String orderName;

  /// **결제 금액**
  ///
  /// 결제 금액을 정수로 나타냅니다.
  ///
  /// 해외 통화의 경우 통화의 최소 단위(minor unit)를 기준으로 합니다. 예를 들어, USD의 최소 단위는 센트(0.01 USD)이므로, 6 USD의 경우 100배하여 600으로 입력합니다.
  ///
  /// 최소 단위는 [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)에 표준화된 것을 기준으로 합니다.
  ///
  /// - KRW: 1배
  /// - USD: 100배
  /// - JPY: 1배
  final int totalAmount;

  /// **화폐**
  ///
  /// [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) 화폐 코드
  ///
  /// 대한민국 원, 일본 엔이 아닌 화폐를 사용할 때에는 금액을 minor unit 단위로 입력해야 함에 유의하세요.
  final Currency currency;

  /// **채널 키**
  ///
  /// 포트원에 등록된 결제 채널 중 하나를 지정합니다.
  ///
  /// [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel)에서 채널 연동 후 채널 키를 확인할 수 있습니다.
  ///
  /// 채널 키와 채널 그룹 ID 중 하나를 지정해야 합니다.
  final String? channelKey;

  /// 빌링키 발급 및 초회결제 수단
  final BillingKeyAndPayMethod billingKeyAndPayMethod;

  /// **면세 금액**
  ///
  /// 미입력 시 0으로 취급됩니다.
  final int? taxFreeAmount;

  /// **부가세 금액**
  ///
  /// 미입력 시 과세 금액의 1/11로 자동 계산됩니다.
  final int? vatAmount;
  final Customer? customer;

  /// **구매 상품 정보**
  final List<Product>? products;

  /// **환경 별 제공되는 결제/본인인증 창 유형**
  ///
  /// - PG사에 따라 가능한 창 유형이 다릅니다.
  /// - 전달되지 않았을 때 결정되는 기본 창이 다릅니다.
  /// - 미입력 시, 해당 PG사의 기본 창 방식을 따릅니다.
  final WindowTypes? windowType;

  /// **결과 리턴 방식을 리디렉션으로 강제**
  ///
  /// `true`로 설정하면 원래 프로미스로 resolve 되었을 상황에서도
  /// `redirectUrl`로 쿼리 파라미터와 함께 리디렉션합니다.
  ///
  /// - `redirectUrl`이 없으면 기존처럼 프로미스로 반환합니다.
  /// - 빌링키 발급 및 결제 시작 전 발생하는 에러는 리디렉션하지 않습니다.
  final bool? forceRedirect;

  /// **웹훅 URL**
  ///
  /// 웹훅을 받을 URL 목록입니다. 값이 있으면 관리자 콘솔에 설정한 URL로는 웹훅이 발송되지 않습니다.
  final List<String>? noticeUrls;

  /// **UI 언어**
  ///
  /// KG이니시스, 스마트로, KSNET, 웰컴페이먼츠 (PC), 한국결제네트웍스, 엑심베이, Triple-A에서 설정 가능하며, PG마다 지원하는 언어 목록은 차이가 있습니다.
  final Locale? locale;

  /// **문화비 지출 여부**
  ///
  /// 도서, 공연, 박물관 등 문화비 지출 여부
  final bool? isCulturalExpense;

  /// **결제 정보와 함께 관리하고 싶은 고객사 커스텀 JSON 데이터**
  final Object? customData;

  /// **서비스 제공 기간**
  ///
  /// range와 interval 중 하나를 입력해주세요.
  ///
  /// - range: 제공 기간 범위
  /// - interval: 제공 기간 주기
  ///
  /// 예1) 2023년 1월 1일 00시 00분 00초(KST) ~
  ///
  /// ```js
  /// range: {
  /// from: '2023-01-01T00:00:00+09:00'
  /// }
  /// ```
  ///
  /// 예2) ~ 2023년 1월 1일 00시 00분 00초(KST)
  ///
  /// ```js
  /// range: {
  /// to: '2023-01-01T00:00:00+09:00'
  /// }
  /// ```
  ///
  /// 예3) 2023년 1월 1일 00시 00분 00초(KST) ~ 2023년 12월 31일 23시 59분 59초(KST)
  ///
  /// ```js
  /// range: {
  /// from: '2023-12-31T23:59:59+09:00'
  /// to: '2023-01-01T00:00:00+09:00'
  /// }
  /// ```
  ///
  /// 예4) 30일 주기
  /// `interval: '30d'`
  ///
  /// 예5) 6개월 주기
  /// `interval: '6m'`
  ///
  /// 예6) 1년 주기
  /// `interval: '1y'`
  final OfferPeriod? offerPeriod;

  /// **앱 URL 스킴**
  final String appScheme;

  /// **상품 유형**
  final ProductType? productType;

  /// **상점 정보**
  ///
  /// - KSNET 카카오페이의 경우 필수 입력
  /// - 나이스페이먼츠의 경우 매출 전표에 표기 할 용도로 선택 입력
  /// - KG이니시스 일본결제의 경우 JPPG(gmoPayment) 결제의 상점정보로 사용되거나 편의점 결제 시 영수증 표시 정보로 사용됨.
  final StoreDetails? storeDetails;

  /// **국가**
  ///
  /// [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
  final Country? country;
  final IssueBillingKeyAndPayBypass? bypass;

  /// **팝업 관련 필드**
  ///
  /// UI가 팝업 창으로 열릴 때 적용되는 속성입니다.
  final Popup? popup;

  /// **결제창이 iframe 방식일 경우 결제창에 적용할 속성**
  final Iframe? iframe;
  final IssueBillingKeyAndPayRequestUnionMobile? mobile;

  IssueBillingKeyAndPayRequest({
    required this.storeId,
    required this.paymentId,
    required this.orderName,
    required this.totalAmount,
    required this.currency,
    this.channelKey,
    required this.billingKeyAndPayMethod,
    this.taxFreeAmount,
    this.vatAmount,
    this.customer,
    this.products,
    this.windowType,
    this.forceRedirect,
    this.noticeUrls,
    this.locale,
    this.isCulturalExpense,
    this.customData,
    this.offerPeriod,
    required this.appScheme,
    this.productType,
    this.storeDetails,
    this.country,
    this.bypass,
    this.popup,
    this.iframe,
    this.mobile,
  });

  Map<String, dynamic> toJson() => {
    'storeId': storeId,
    'paymentId': paymentId,
    'orderName': orderName,
    'totalAmount': totalAmount,
    'currency': currency.toJson(),
    if (channelKey != null) 'channelKey': channelKey!,
    'billingKeyAndPayMethod': billingKeyAndPayMethod.toJson(),
    if (taxFreeAmount != null) 'taxFreeAmount': taxFreeAmount!,
    if (vatAmount != null) 'vatAmount': vatAmount!,
    if (customer != null) 'customer': customer!.toJson(),
    if (products != null) 'products': products!.map((e) => e.toJson()).toList(),
    if (windowType != null) 'windowType': windowType!.toJson(),
    if (forceRedirect != null) 'forceRedirect': forceRedirect!,
    if (noticeUrls != null) 'noticeUrls': noticeUrls!,
    if (locale != null) 'locale': locale!.toJson(),
    if (isCulturalExpense != null) 'isCulturalExpense': isCulturalExpense!,
    if (customData != null) 'customData': customData!,
    if (offerPeriod != null) 'offerPeriod': offerPeriod!.toJson(),
    'appScheme': appScheme,
    if (productType != null) 'productType': productType!.toJson(),
    if (storeDetails != null) 'storeDetails': storeDetails!.toJson(),
    if (country != null) 'country': country!.toJson(),
    if (bypass != null) 'bypass': bypass!.toJson(),
    if (popup != null) 'popup': popup!.toJson(),
    if (iframe != null) 'iframe': iframe!.toJson(),
    if (mobile != null) 'mobile': mobile!.toJson(),
  };
}
