// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/card_company.dart';
import 'package:portone_flutter/v2/model/entity/easy_pay_payment_method.dart';
import 'package:portone_flutter/v2/model/entity/easy_pay_provider.dart';

class IssueBillingKeyRequestUnionEasyPay {
  final List<CardCompany>? availableCards;

  /// PG 제휴로 간편결제를 이용할 때, 간편결제 UI를 직접 호출할 수 있는 간편결제
  final EasyPayProvider? easyPayProvider;

  /// 노출을 허용할 결제 수단의 종류
  final List<EasyPayPaymentMethod>? availablePayMethods;

  IssueBillingKeyRequestUnionEasyPay({
    this.availableCards,
    this.easyPayProvider,
    this.availablePayMethods,
  });

  Map<String, dynamic> toJson() => {
    if (availableCards != null)
      'availableCards': availableCards!.map((e) => e.toJson()).toList(),
    if (easyPayProvider != null) 'easyPayProvider': easyPayProvider!.toJson(),
    if (availablePayMethods != null)
      'availablePayMethods':
          availablePayMethods!.map((e) => e.toJson()).toList(),
  };

  static IssueBillingKeyRequestUnionEasyPay fromJson(
    Map<String, dynamic> json,
  ) => IssueBillingKeyRequestUnionEasyPay(
    availableCards:
        (json['availableCards'] as List?)
            ?.map((e) => CardCompany.fromJson(e))
            .toList(),
    easyPayProvider:
        json['easyPayProvider'] != null
            ? EasyPayProvider.fromJson(json['easyPayProvider'])
            : null,
    availablePayMethods:
        (json['availablePayMethods'] as List?)
            ?.map((e) => EasyPayPaymentMethod.fromJson(e))
            .toList(),
  );
}
