// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class IssueBillingKeyRequestUnionPaypal {
  Map<String, dynamic> toJson() => {};
  static IssueBillingKeyRequestUnionPaypal fromJson(
    Map<String, dynamic> json,
  ) => IssueBillingKeyRequestUnionPaypal();
}
