// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/billing_key_method.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_issue_billing_key_ui_bypass.dart';
import 'package:portone_flutter/v2/model/entity/currency.dart';
import 'package:portone_flutter/v2/model/entity/customer.dart';
import 'package:portone_flutter/v2/model/entity/issue_billing_key_ui_type.dart';
import 'package:portone_flutter/v2/model/entity/locale.dart';
import 'package:portone_flutter/v2/model/entity/product_type.dart';

class LoadIssueBillingKeyUIRequest {
  final IssueBillingKeyUIType uiType;

  /// 빌링 등록 UI에 표시되는 금액
  final int? displayAmount;

  /// **화폐**
  ///
  /// [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) 화폐 코드
  ///
  /// 대한민국 원, 일본 엔이 아닌 화폐를 사용할 때에는 금액을 minor unit 단위로 입력해야 함에 유의하세요.
  final Currency? currency;

  /// **상점 아이디**
  ///
  /// 포트원 계정에 생성된 상점을 식별하는 고유한 값으로 [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel) 우측 상단에서 확인할 수 있습니다.
  final String storeId;

  /// **채널 키**
  ///
  /// 포트원에 등록된 결제 채널 중 하나를 지정합니다.
  ///
  /// [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel)에서 채널 연동 후 채널 키를 확인할 수 있습니다.
  ///
  /// 채널 키와 채널 그룹 ID 중 하나를 지정해야 합니다.
  final String channelKey;

  /// 빌링키 발급 수단
  final BillingKeyMethod billingKeyMethod;

  /// **주문명**
  final String? issueName;

  /// **빌링 등록 주문 번호**
  final String? issueId;
  final Customer? customer;

  /// **UI 언어**
  ///
  /// KG이니시스, 스마트로, KSNET, 웰컴페이먼츠 (PC), 한국결제네트웍스, 엑심베이, Triple-A, 페이먼트월에서 설정 가능하며, PG마다 지원하는 언어 목록은 차이가 있습니다.
  final Locale? locale;

  /// **빌링키 커스텀 JSON 데이터**
  ///
  /// 자유롭게 데이터를 넣어 이후 조회할 수 있습니다.
  final Object? customData;

  /// **앱 URL 스킴**
  final String appScheme;

  /// **웹훅 URL**
  final List<String>? noticeUrls;

  /// **상품 유형**
  final ProductType? productType;
  final LoadIssueBillingKeyUIBypass? bypass;

  LoadIssueBillingKeyUIRequest({
    required this.uiType,
    this.displayAmount,
    this.currency,
    required this.storeId,
    required this.channelKey,
    required this.billingKeyMethod,
    this.issueName,
    this.issueId,
    this.customer,
    this.locale,
    this.customData,
    required this.appScheme,
    this.noticeUrls,
    this.productType,
    this.bypass,
  });

  Map<String, dynamic> toJson() => {
    'uiType': uiType.toJson(),
    if (displayAmount != null) 'displayAmount': displayAmount!,
    if (currency != null) 'currency': currency!.toJson(),
    'storeId': storeId,
    'channelKey': channelKey,
    'billingKeyMethod': billingKeyMethod.toJson(),
    if (issueName != null) 'issueName': issueName!,
    if (issueId != null) 'issueId': issueId!,
    if (customer != null) 'customer': customer!.toJson(),
    if (locale != null) 'locale': locale!.toJson(),
    if (customData != null) 'customData': customData!,
    'appScheme': appScheme,
    if (noticeUrls != null) 'noticeUrls': noticeUrls!,
    if (productType != null) 'productType': productType!.toJson(),
    if (bypass != null) 'bypass': bypass!.toJson(),
  };
}
