// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/easy_pay_provider.dart';

class PaymentRequestUnionAlipayPlus {
  /// PG 제휴로 간편결제를 이용할 때, 간편결제 UI를 직접 호출할 수 있는 간편결제
  final EasyPayProvider? easyPayProvider;

  PaymentRequestUnionAlipayPlus({this.easyPayProvider});

  Map<String, dynamic> toJson() => {
    if (easyPayProvider != null) 'easyPayProvider': easyPayProvider!.toJson(),
  };
}
