// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **고정식 가상계좌 설정**
sealed class PaymentRequestUnionVirtualAccountFixedOption {
  Map<String, dynamic> toJson();
}

/// PG사로부터 사전에 가상계좌에 대한 ID를 발급받아 사용하는 경우의 가상계좌 ID
class PaymentRequestUnionVirtualAccountFixedOptionPgAccountId
    extends PaymentRequestUnionVirtualAccountFixedOption {
  final String pgAccountId;
  PaymentRequestUnionVirtualAccountFixedOptionPgAccountId(this.pgAccountId);
  @override
  Map<String, dynamic> toJson() => {'pgAccountId': pgAccountId};
}

/// 고정식으로 사용할 가상계좌 번호
class PaymentRequestUnionVirtualAccountFixedOptionAccountNumber
    extends PaymentRequestUnionVirtualAccountFixedOption {
  final String accountNumber;
  PaymentRequestUnionVirtualAccountFixedOptionAccountNumber(this.accountNumber);
  @override
  Map<String, dynamic> toJson() => {'accountNumber': accountNumber};
}
