// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **편의점결제 지불기한**
sealed class PaymentRequestUnionConvenienceStorePaymentDeadline {
  Map<String, dynamic> toJson();
  static PaymentRequestUnionConvenienceStorePaymentDeadline fromJson(
    Map<String, dynamic> json,
  ) {
    if (json.containsKey('validHours'))
      return PaymentRequestUnionConvenienceStorePaymentDeadlineValidHours.fromJson(
        json,
      );
    if (json.containsKey('dueDate'))
      return PaymentRequestUnionConvenienceStorePaymentDeadlineDueDate.fromJson(
        json,
      );
    throw ArgumentError(
      'Unknown PaymentRequestUnionConvenienceStorePaymentDeadline variant',
    );
  }
}

/// **유효 시간 (단위: 시간)**
class PaymentRequestUnionConvenienceStorePaymentDeadlineValidHours
    extends PaymentRequestUnionConvenienceStorePaymentDeadline {
  final int validHours;
  PaymentRequestUnionConvenienceStorePaymentDeadlineValidHours(this.validHours);
  static PaymentRequestUnionConvenienceStorePaymentDeadlineValidHours fromJson(
    Map<String, dynamic> json,
  ) => PaymentRequestUnionConvenienceStorePaymentDeadlineValidHours(
    json['validHours'] as int,
  );
  @override
  Map<String, dynamic> toJson() => {'validHours': validHours};
}

/// **만료일시**
///
/// RFC 3339 형식입니다.
class PaymentRequestUnionConvenienceStorePaymentDeadlineDueDate
    extends PaymentRequestUnionConvenienceStorePaymentDeadline {
  final String dueDate;
  PaymentRequestUnionConvenienceStorePaymentDeadlineDueDate(this.dueDate);
  static PaymentRequestUnionConvenienceStorePaymentDeadlineDueDate fromJson(
    Map<String, dynamic> json,
  ) => PaymentRequestUnionConvenienceStorePaymentDeadlineDueDate(
    json['dueDate'] as String,
  );
  @override
  Map<String, dynamic> toJson() => {'dueDate': dueDate};
}
