// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/carrier.dart';

/// **휴대전화 결제 설정**
class PaymentRequestUnionMobile {
  /// 통신사 코드
  final Carrier? carrier;

  /// **일부 통신사만 노출 설정**
  ///
  /// 일부 통신사만을 선택 가능하게 하고 싶은 경우 사용하는 옵션입니다.
  final List<Carrier>? avaliableCarriers;

  PaymentRequestUnionMobile({this.carrier, this.avaliableCarriers});

  Map<String, dynamic> toJson() => {
    if (carrier != null) 'carrier': carrier!.toJson(),
    if (avaliableCarriers != null)
      'avaliableCarriers': avaliableCarriers!.map((e) => e.toJson()).toList(),
  };

  static PaymentRequestUnionMobile fromJson(Map<String, dynamic> json) =>
      PaymentRequestUnionMobile(
        carrier:
            json['carrier'] != null ? Carrier.fromJson(json['carrier']) : null,
        avaliableCarriers:
            (json['avaliableCarriers'] as List?)
                ?.map((e) => Carrier.fromJson(e))
                .toList(),
      );
}
