// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/gift_certificate_type.dart';

/// **상품권 결제 설정**
class PaymentRequestUnionGiftCertificate {
  /// **상품권 종류**
  final GiftCertificateType? giftCertificateType;

  PaymentRequestUnionGiftCertificate({this.giftCertificateType});

  Map<String, dynamic> toJson() => {
    if (giftCertificateType != null)
      'giftCertificateType': giftCertificateType!.toJson(),
  };

  static PaymentRequestUnionGiftCertificate fromJson(
    Map<String, dynamic> json,
  ) => PaymentRequestUnionGiftCertificate(
    giftCertificateType:
        json['giftCertificateType'] != null
            ? GiftCertificateType.fromJson(json['giftCertificateType'])
            : null,
  );
}
