// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/card_company.dart';
import 'package:portone_flutter/v2/model/entity/card_promotion.dart';
import 'package:portone_flutter/v2/model/entity/installment.dart';

/// **카드 결제 설정**
class PaymentRequestUnionCard {
  /// 카드 결제시 사용되는 카드사 코드
  final CardCompany? cardCompany;

  /// **일부 카드사만 노출 설정**
  ///
  /// 일부 카드사만을 선택 가능하게 하고 싶은 경우 사용하는 옵션입니다.
  final List<CardCompany>? availableCards;

  /// **상점분담 무이자 활성화 여부**
  final bool? useFreeInterestFromMall;

  /// **할부 설정**
  ///
  /// 신용카드 결제 시 할부 관련 설정을 제어합니다.
  ///
  /// ## 사용 예시
  ///
  /// ### 3개월 고정 할부
  ///
  /// ```typescript
  /// installment: {
  /// monthOption: {
  /// fixedMonth: 3
  /// }
  /// }
  /// ```
  ///
  /// ### 2~6개월 할부 선택
  ///
  /// ```typescript
  /// installment: {
  /// monthOption: {
  /// availableMonthList: [2, 3, 4, 5, 6]
  /// }
  /// }
  /// ```
  ///
  /// ### 무이자 할부 설정 (삼성카드 2,3개월)
  ///
  /// ```typescript
  /// installment: {
  /// freeInstallmentPlans: [{
  /// cardCompany: 'CARD_COMPANY_SAMSUNG',
  /// months: [2, 3]
  /// }]
  /// }
  /// ```
  ///
  /// ## 주의사항
  ///
  /// - 일반적으로 5만원 이상부터 할부가 가능합니다
  /// - 1개월 할부는 일시불과 동일하게 처리됩니다
  /// - 카드 다이렉트 호출 시 고정 할부만 가능한 PG사가 있습니다
  /// - 무이자 할부는 가맹점이 수수료를 부담하는 방식입니다
  final Installment? installment;

  /// **카드 포인트 사용 설정**
  final bool? useCardPoint;

  /// **앱 카드만 허용할지 여부**
  final bool? useAppCardOnly;

  /// 할부 사용 가능 여부
  final bool? useInstallment;

  /// **카드 프로모션 정보**
  ///
  /// 카드사 다이렉트 호출 시 적용할 카드사 할인 쿠폰 정보입니다.
  ///
  /// 현재 KCP\_V2 채널에서만 사용 가능합니다.
  final CardPromotion? cardPromotion;

  PaymentRequestUnionCard({
    this.cardCompany,
    this.availableCards,
    this.useFreeInterestFromMall,
    this.installment,
    this.useCardPoint,
    this.useAppCardOnly,
    this.useInstallment,
    this.cardPromotion,
  });

  Map<String, dynamic> toJson() => {
    if (cardCompany != null) 'cardCompany': cardCompany!.toJson(),
    if (availableCards != null)
      'availableCards': availableCards!.map((e) => e.toJson()).toList(),
    if (useFreeInterestFromMall != null)
      'useFreeInterestFromMall': useFreeInterestFromMall!,
    if (installment != null) 'installment': installment!.toJson(),
    if (useCardPoint != null) 'useCardPoint': useCardPoint!,
    if (useAppCardOnly != null) 'useAppCardOnly': useAppCardOnly!,
    if (useInstallment != null) 'useInstallment': useInstallment!,
    if (cardPromotion != null) 'cardPromotion': cardPromotion!.toJson(),
  };

  static PaymentRequestUnionCard fromJson(Map<String, dynamic> json) =>
      PaymentRequestUnionCard(
        cardCompany:
            json['cardCompany'] != null
                ? CardCompany.fromJson(json['cardCompany'])
                : null,
        availableCards:
            (json['availableCards'] as List?)
                ?.map((e) => CardCompany.fromJson(e))
                .toList(),
        useFreeInterestFromMall: json['useFreeInterestFromMall'] as bool?,
        installment:
            json['installment'] != null
                ? Installment.fromJson(json['installment'])
                : null,
        useCardPoint: json['useCardPoint'] as bool?,
        useAppCardOnly: json['useAppCardOnly'] as bool?,
        useInstallment: json['useInstallment'] as bool?,
        cardPromotion:
            json['cardPromotion'] != null
                ? CardPromotion.fromJson(json['cardPromotion'])
                : null,
      );
}
