// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **편의점결제 지불기한**
sealed class PaymentRequestUnionConvenienceStorePaymentDeadline {
  Map<String, dynamic> toJson();
}

/// **유효 시간 (단위: 시간)**
class PaymentRequestUnionConvenienceStorePaymentDeadlineValidHours
    extends PaymentRequestUnionConvenienceStorePaymentDeadline {
  final int validHours;
  PaymentRequestUnionConvenienceStorePaymentDeadlineValidHours(this.validHours);
  @override
  Map<String, dynamic> toJson() => {'validHours': validHours};
}

/// **만료일시**
///
/// RFC 3339 형식입니다.
class PaymentRequestUnionConvenienceStorePaymentDeadlineDueDate
    extends PaymentRequestUnionConvenienceStorePaymentDeadline {
  final String dueDate;
  PaymentRequestUnionConvenienceStorePaymentDeadlineDueDate(this.dueDate);
  @override
  Map<String, dynamic> toJson() => {'dueDate': dueDate};
}
