// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bank.dart';
import 'package:portone_flutter/v2/model/entity/cash_receipt_type.dart';

/// **계좌이체 결제 설정**
class PaymentRequestUnionTransfer {
  /// **현금영수증 발급 유형**
  final CashReceiptType? cashReceiptType;

  /// **현금영수증 구매자 번호**
  ///
  /// 카드일련번호, 주민등록번호, 사업자등록번호, 휴대전화번호 중 하나입니다. NICE페이먼츠와 스마트로에서 PG UI를 건너뛸 때 사용합니다.
  final String? customerIdentifier;

  /// 가상계좌 발급시 사용되는 은행 코드
  final Bank? bankCode;

  PaymentRequestUnionTransfer({
    this.cashReceiptType,
    this.customerIdentifier,
    this.bankCode,
  });

  Map<String, dynamic> toJson() => {
    if (cashReceiptType != null) 'cashReceiptType': cashReceiptType!.toJson(),
    if (customerIdentifier != null) 'customerIdentifier': customerIdentifier!,
    if (bankCode != null) 'bankCode': bankCode!.toJson(),
  };
}
