// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/request/payment_request_union_convenience_store_payment_deadline.dart';

class PaymentRequestUnionConvenienceStore {
  /// **편의점결제 지불기한**
  final PaymentRequestUnionConvenienceStorePaymentDeadline? paymentDeadline;

  PaymentRequestUnionConvenienceStore({this.paymentDeadline});

  Map<String, dynamic> toJson() => {
    if (paymentDeadline != null) 'paymentDeadline': paymentDeadline!.toJson(),
  };
}
