// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bank.dart';
import 'package:portone_flutter/v2/model/entity/cash_receipt_type.dart';
import 'package:portone_flutter/v2/model/request/payment_request_union_virtual_account_account_expiry.dart';
import 'package:portone_flutter/v2/model/request/payment_request_union_virtual_account_fixed_option.dart';

/// **가상계좌 결제 설정**
class PaymentRequestUnionVirtualAccount {
  /// **현금영수증 발급 유형**
  final CashReceiptType? cashReceiptType;

  /// **현금영수증 구매자 번호**
  ///
  /// 카드일련번호, 주민등록번호, 사업자등록번호, 휴대전화번호 중 하나입니다. 스마트로에서 PG UI를 건너뛸 때 사용합니다.
  final String? customerIdentifier;

  /// **고정식 가상계좌 설정**
  final PaymentRequestUnionVirtualAccountFixedOption? fixedOption;

  /// 가상계좌 발급시 사용되는 은행 코드
  final Bank? bankCode;

  /// **가상계좌 입금 만료 기한**
  ///
  /// 토스페이먼츠, KG이니시스, NHN KCP에서 지원합니다.
  ///
  /// `validHours`와 `dueDate` 중 하나만 지정합니다.
  final PaymentRequestUnionVirtualAccountAccountExpiry? accountExpiry;

  /// **선택 가능 은행 목록**
  ///
  /// 가상계좌 발급 UI에서 선택할 수 있는 은행 목록을 지정합니다. KCP에서만 지원합니다.
  final List<Bank>? availableBanks;

  PaymentRequestUnionVirtualAccount({
    this.cashReceiptType,
    this.customerIdentifier,
    this.fixedOption,
    this.bankCode,
    this.accountExpiry,
    this.availableBanks,
  });

  Map<String, dynamic> toJson() => {
    if (cashReceiptType != null) 'cashReceiptType': cashReceiptType!.toJson(),
    if (customerIdentifier != null) 'customerIdentifier': customerIdentifier!,
    if (fixedOption != null) 'fixedOption': fixedOption!.toJson(),
    if (bankCode != null) 'bankCode': bankCode!.toJson(),
    if (accountExpiry != null) 'accountExpiry': accountExpiry!.toJson(),
    if (availableBanks != null)
      'availableBanks': availableBanks!.map((e) => e.toJson()).toList(),
  };
}
