// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class PaymentRequestUnionAlipay {
  Map<String, dynamic> toJson() => {};
  static PaymentRequestUnionAlipay fromJson(Map<String, dynamic> json) =>
      PaymentRequestUnionAlipay();
}
