// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

class PaymentRequestUnionPaypal {
  Map<String, dynamic> toJson() => {};
  static PaymentRequestUnionPaypal fromJson(Map<String, dynamic> json) =>
      PaymentRequestUnionPaypal();
}
