// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 버튼 라벨
enum PaypalV2StyleLabel {
  paypal('paypal'),
  checkout('checkout'),
  buynow('buynow'),
  pay('pay'),
  installment('installment'),
  subscribe('subscribe'),
  donate('donate');

  final String _value;
  const PaypalV2StyleLabel(String value) : _value = value;
  String toJson() => _value;
}
