// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_purchase_unit_shipping.dart';

class PaypalV2PurchaseUnit {
  /// 구매 상품 정보
  final PaypalV2PurchaseUnitShipping? shipping;

  PaypalV2PurchaseUnit({this.shipping});

  Map<String, dynamic> toJson() => {
    if (shipping != null) 'shipping': shipping!.toJson(),
  };

  static PaypalV2PurchaseUnit fromJson(Map<String, dynamic> json) =>
      PaypalV2PurchaseUnit(
        shipping:
            json['shipping'] != null
                ? PaypalV2PurchaseUnitShipping.fromJson(json['shipping'])
                : null,
      );
}
