// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_payer_address.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_payer_tax_info.dart';

class PaypalV2Payer {
  /// 구매자 정보
  final PaypalV2PayerTaxInfo? taxInfo;
  final PaypalV2PayerAddress? address;

  PaypalV2Payer({this.taxInfo, this.address});

  Map<String, dynamic> toJson() => {
    if (taxInfo != null) 'tax_info': taxInfo!.toJson(),
    if (address != null) 'address': address!.toJson(),
  };
}
