// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/country.dart';

/// 수령지 정보
class PaypalV2PurchaseUnitShippingAddress {
  /// 수령지 주소. 미 입력 시 입력된 주소로 override되지 않음
  final String addressLine1;
  final String? addressLine2;
  final String? adminArea1;

  /// 필수 입력. 미 입력 시 create order 실패
  final String adminArea2;
  final String? postalCode;

  /// **국가**
  ///
  /// [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
  final Country countryCode;

  PaypalV2PurchaseUnitShippingAddress({
    required this.addressLine1,
    this.addressLine2,
    this.adminArea1,
    required this.adminArea2,
    this.postalCode,
    required this.countryCode,
  });

  Map<String, dynamic> toJson() => {
    'address_line_1': addressLine1,
    if (addressLine2 != null) 'address_line_2': addressLine2!,
    if (adminArea1 != null) 'admin_area_1': adminArea1!,
    'admin_area_2': adminArea2,
    if (postalCode != null) 'postal_code': postalCode!,
    'country_code': countryCode.toJson(),
  };

  static PaypalV2PurchaseUnitShippingAddress fromJson(
    Map<String, dynamic> json,
  ) => PaypalV2PurchaseUnitShippingAddress(
    addressLine1: json['address_line_1'] as String,
    addressLine2: json['address_line_2'] as String?,
    adminArea1: json['admin_area_1'] as String?,
    adminArea2: json['admin_area_2'] as String,
    postalCode: json['postal_code'] as String?,
    countryCode: Country.fromJson(json['country_code']),
  );
}
