// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_purchase_unit_shipping_address.dart';

/// 구매 상품 정보
class PaypalV2PurchaseUnitShipping {
  /// 수령지 정보
  final PaypalV2PurchaseUnitShippingAddress? address;

  PaypalV2PurchaseUnitShipping({this.address});

  Map<String, dynamic> toJson() => {
    if (address != null) 'address': address!.toJson(),
  };

  static PaypalV2PurchaseUnitShipping fromJson(Map<String, dynamic> json) =>
      PaypalV2PurchaseUnitShipping(
        address:
            json['address'] != null
                ? PaypalV2PurchaseUnitShippingAddress.fromJson(json['address'])
                : null,
      );
}
