// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/country.dart';

class PaypalV2PayerAddress {
  /// 구매자 주소지 정보
  final String? addressLine1;
  final String? addressLine2;
  final String? adminArea1;
  final String? adminArea2;

  /// 우편번호
  final String? postalCode;

  /// **국가**
  ///
  /// [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
  final Country countryCode;

  PaypalV2PayerAddress({
    this.addressLine1,
    this.addressLine2,
    this.adminArea1,
    this.adminArea2,
    this.postalCode,
    required this.countryCode,
  });

  Map<String, dynamic> toJson() => {
    if (addressLine1 != null) 'address_line_1': addressLine1!,
    if (addressLine2 != null) 'address_line_2': addressLine2!,
    if (adminArea1 != null) 'admin_area_1': adminArea1!,
    if (adminArea2 != null) 'admin_area_2': adminArea2!,
    if (postalCode != null) 'postal_code': postalCode!,
    'country_code': countryCode.toJson(),
  };

  static PaypalV2PayerAddress fromJson(Map<String, dynamic> json) =>
      PaypalV2PayerAddress(
        addressLine1: json['address_line_1'] as String?,
        addressLine2: json['address_line_2'] as String?,
        adminArea1: json['admin_area_1'] as String?,
        adminArea2: json['admin_area_2'] as String?,
        postalCode: json['postal_code'] as String?,
        countryCode: Country.fromJson(json['country_code']),
      );
}
