// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 버튼 색상
enum PaypalV2StyleColor {
  gold('gold'),
  blue('blue'),
  silver('silver'),
  white('white'),
  black('black');

  final String _value;
  const PaypalV2StyleColor(String value) : _value = value;
  String toJson() => _value;
}
