// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 버튼 모양
enum PaypalV2StyleShape {
  rect('rect'),
  pill('pill');

  final String _value;
  const PaypalV2StyleShape(String value) : _value = value;
  String toJson() => _value;
  static PaypalV2StyleShape fromJson(String value) =>
      values.firstWhere((e) => e._value == value);
}
