// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_additional_data.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_payer.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_purchase_unit.dart';
import 'package:portone_flutter/v2/model/entity/bypass/load_payment_ui/paypal_v_2_style.dart';

/// **Paypal bypass 파라미터**
class PaypalV2LoadPaymentUIBypass {
  /// SPB 버튼 렌더링에 필요한 파라미터
  final PaypalV2Style? style;

  /// 허용할 결제 수단 (예: "card, credit, bancontact")
  final String? enableFunding;

  /// 차단할 결제 수단 (예: "venmo, mercadopago")
  final String? disableFunding;

  /// create order API 호출에 필요한 파라미터
  final List<PaypalV2PurchaseUnit>? purchaseUnits;
  final PaypalV2Payer? payer;

  /// STC 파라미터
  final List<PaypalV2AdditionalData>? additionalData;

  PaypalV2LoadPaymentUIBypass({
    this.style,
    this.enableFunding,
    this.disableFunding,
    this.purchaseUnits,
    this.payer,
    this.additionalData,
  });

  Map<String, dynamic> toJson() => {
    if (style != null) 'style': style!.toJson(),
    if (enableFunding != null) 'enable-funding': enableFunding!,
    if (disableFunding != null) 'disable-funding': disableFunding!,
    if (purchaseUnits != null)
      'purchase_units': purchaseUnits!.map((e) => e.toJson()).toList(),
    if (payer != null) 'payer': payer!.toJson(),
    if (additionalData != null)
      'additional_data': additionalData!.map((e) => e.toJson()).toList(),
  };
}
