// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// 구매자 정보
class PaypalV2PayerTaxInfo {
  /// 구매자 세금 정보 (브라질 구매자의 경우 필수 입력)
  final String taxId;
  final String taxIdType;

  PaypalV2PayerTaxInfo({required this.taxId, required this.taxIdType});

  Map<String, dynamic> toJson() => {'tax_id': taxId, 'tax_id_type': taxIdType};
}
