// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **리디렉션 없이 결제 UI가 표시된 경우 반환값**
class IdentityVerificationResponse {
  /// **트랜잭션 유형**
  ///
  /// 본인인증의 경우 경우 항상 `IDENTITY_VERIFICATION`으로 전달됩니다.
  final String transactionType;

  /// **본인인증 ID**
  ///
  /// 본인인증 ID입니다.
  final String identityVerificationId;

  /// **본인인증 시도 ID**
  ///
  /// 요청마다 고유하게 생성되는 본인인증 시도 ID입니다.
  final String identityVerificationTxId;

  /// **오류 코드**
  ///
  /// 실패한 경우 오류 코드입니다.
  final String? code;

  /// **오류 메시지**
  ///
  /// 실패한 경우 오류 메시지입니다.
  final String? message;

  /// **PG 오류 코드**
  ///
  /// PG에서 오류 코드를 내려 주는 경우 이 오류 코드를 그대로 반환합니다.
  final String? pgCode;

  /// **PG 오류 메시지**
  ///
  /// PG에서 오류 메시지를 내려 주는 경우 이 오류 메시지를 그대로 반환합니다.
  final String? pgMessage;

  IdentityVerificationResponse({
    required this.transactionType,
    required this.identityVerificationId,
    required this.identityVerificationTxId,
    this.code,
    this.message,
    this.pgCode,
    this.pgMessage,
  });

  Map<String, dynamic> toJson() => {
    'transactionType': transactionType,
    'identityVerificationId': identityVerificationId,
    'identityVerificationTxId': identityVerificationTxId,
    if (code != null) 'code': code!,
    if (message != null) 'message': message!,
    if (pgCode != null) 'pgCode': pgCode!,
    if (pgMessage != null) 'pgMessage': pgMessage!,
  };

  static IdentityVerificationResponse fromJson(Map<String, dynamic> json) =>
      IdentityVerificationResponse(
        transactionType: json['transactionType'] as String,
        identityVerificationId: json['identityVerificationId'] as String,
        identityVerificationTxId: json['identityVerificationTxId'] as String,
        code: json['code'] as String?,
        message: json['message'] as String?,
        pgCode: json['pgCode'] as String?,
        pgMessage: json['pgMessage'] as String?,
      );
}
