// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **리디렉션 없이 빌링키 발급 UI가 표시된 경우 반환값**
class IssueBillingKeyResponse {
  /// `ISSUE_BILLING_KEY`
  final String transactionType;

  /// **빌링키**
  ///
  /// 빌링 결제를 일으킬 때 사용하는 빌링키입니다. 수동 승인 사용시 'NEEDS\_CONFIRMATION'으로 전달됩니다.
  final String billingKey;

  /// 수동 승인 사용시 수동 승인 API 호출에 필요한 토큰입니다.
  final String? billingIssueToken;

  /// **오류 코드**
  ///
  /// 실패한 경우 오류 코드입니다.
  final String? code;

  /// **오류 메시지**
  ///
  /// 실패한 경우 오류 메시지입니다.
  final String? message;

  /// **PG 오류 코드**
  ///
  /// PG에서 오류 코드를 내려 주는 경우 이 오류 코드를 그대로 반환합니다.
  final String? pgCode;

  /// **PG 오류 메시지**
  ///
  /// PG에서 오류 메시지를 내려 주는 경우 이 오류 메시지를 그대로 반환합니다.
  final String? pgMessage;

  IssueBillingKeyResponse({
    required this.transactionType,
    required this.billingKey,
    this.billingIssueToken,
    this.code,
    this.message,
    this.pgCode,
    this.pgMessage,
  });

  Map<String, dynamic> toJson() => {
    'transactionType': transactionType,
    'billingKey': billingKey,
    if (billingIssueToken != null) 'billingIssueToken': billingIssueToken!,
    if (code != null) 'code': code!,
    if (message != null) 'message': message!,
    if (pgCode != null) 'pgCode': pgCode!,
    if (pgMessage != null) 'pgMessage': pgMessage!,
  };

  static IssueBillingKeyResponse fromJson(Map<String, dynamic> json) =>
      IssueBillingKeyResponse(
        transactionType: json['transactionType'] as String,
        billingKey: json['billingKey'] as String,
        billingIssueToken: json['billingIssueToken'] as String?,
        code: json['code'] as String?,
        message: json['message'] as String?,
        pgCode: json['pgCode'] as String?,
        pgMessage: json['pgMessage'] as String?,
      );
}
