// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

/// **리디렉션 없이 결제 UI가 표시된 경우 반환값**
class PaymentResponse {
  /// **유형**
  ///
  /// 일반결제의 경우 무조건 `PAYMENT`로 전달됩니다.
  final String transactionType;

  /// **결제 시도 ID**
  ///
  /// 요청마다 고유하게 생성되는 결제 시도 ID입니다.
  final String txId;

  /// **결제 ID**
  final String paymentId;

  /// **결제 토큰**
  ///
  /// 수동 승인 사용시 수동 승인 API 호출에 필요한 토큰입니다.
  final String? paymentToken;

  /// **오류 코드**
  ///
  /// 실패한 경우 오류 코드입니다.
  final String? code;

  /// **오류 메시지**
  ///
  /// 실패한 경우 오류 메시지입니다.
  final String? message;

  /// **PG 오류 코드**
  ///
  /// PG에서 오류 코드를 내려 주는 경우 이 오류 코드를 그대로 반환합니다.
  final String? pgCode;

  /// **PG 오류 메시지**
  ///
  /// PG에서 오류 메시지를 내려 주는 경우 이 오류 메시지를 그대로 반환합니다.
  final String? pgMessage;

  PaymentResponse({
    required this.transactionType,
    required this.txId,
    required this.paymentId,
    this.paymentToken,
    this.code,
    this.message,
    this.pgCode,
    this.pgMessage,
  });

  Map<String, dynamic> toJson() => {
    'transactionType': transactionType,
    'txId': txId,
    'paymentId': paymentId,
    if (paymentToken != null) 'paymentToken': paymentToken!,
    if (code != null) 'code': code!,
    if (message != null) 'message': message!,
    if (pgCode != null) 'pgCode': pgCode!,
    if (pgMessage != null) 'pgMessage': pgMessage!,
  };

  static PaymentResponse fromJson(Map<String, dynamic> json) => PaymentResponse(
    transactionType: json['transactionType'] as String,
    txId: json['txId'] as String,
    paymentId: json['paymentId'] as String,
    paymentToken: json['paymentToken'] as String?,
    code: json['code'] as String?,
    message: json['message'] as String?,
    pgCode: json['pgCode'] as String?,
    pgMessage: json['pgMessage'] as String?,
  );
}
